// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/area"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AreaCreate is the builder for creating a Area entity.
type AreaCreate struct {
	config
	mutation *AreaMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *AreaCreate) SetGameID(v int) *AreaCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_c *AreaCreate) SetAssetbundleName(v string) *AreaCreate {
	_c.mutation.SetAssetbundleName(v)
	return _c
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_c *AreaCreate) SetNillableAssetbundleName(v *string) *AreaCreate {
	if v != nil {
		_c.SetAssetbundleName(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AreaCreate) SetGroupID(v int) *AreaCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *AreaCreate) SetNillableGroupID(v *int) *AreaCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetIsBaseArea sets the "is_base_area" field.
func (_c *AreaCreate) SetIsBaseArea(v bool) *AreaCreate {
	_c.mutation.SetIsBaseArea(v)
	return _c
}

// SetNillableIsBaseArea sets the "is_base_area" field if the given value is not nil.
func (_c *AreaCreate) SetNillableIsBaseArea(v *bool) *AreaCreate {
	if v != nil {
		_c.SetIsBaseArea(*v)
	}
	return _c
}

// SetAreaType sets the "area_type" field.
func (_c *AreaCreate) SetAreaType(v json.RawMessage) *AreaCreate {
	_c.mutation.SetAreaType(v)
	return _c
}

// SetViewType sets the "view_type" field.
func (_c *AreaCreate) SetViewType(v json.RawMessage) *AreaCreate {
	_c.mutation.SetViewType(v)
	return _c
}

// SetDisplayTimelineType sets the "display_timeline_type" field.
func (_c *AreaCreate) SetDisplayTimelineType(v json.RawMessage) *AreaCreate {
	_c.mutation.SetDisplayTimelineType(v)
	return _c
}

// SetAdditionalAreaType sets the "additional_area_type" field.
func (_c *AreaCreate) SetAdditionalAreaType(v json.RawMessage) *AreaCreate {
	_c.mutation.SetAdditionalAreaType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AreaCreate) SetName(v string) *AreaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *AreaCreate) SetNillableName(v *string) *AreaCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetReleaseConditionID sets the "release_condition_id" field.
func (_c *AreaCreate) SetReleaseConditionID(v int) *AreaCreate {
	_c.mutation.SetReleaseConditionID(v)
	return _c
}

// SetNillableReleaseConditionID sets the "release_condition_id" field if the given value is not nil.
func (_c *AreaCreate) SetNillableReleaseConditionID(v *int) *AreaCreate {
	if v != nil {
		_c.SetReleaseConditionID(*v)
	}
	return _c
}

// SetSubName sets the "sub_name" field.
func (_c *AreaCreate) SetSubName(v string) *AreaCreate {
	_c.mutation.SetSubName(v)
	return _c
}

// SetNillableSubName sets the "sub_name" field if the given value is not nil.
func (_c *AreaCreate) SetNillableSubName(v *string) *AreaCreate {
	if v != nil {
		_c.SetSubName(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *AreaCreate) SetLabel(v string) *AreaCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *AreaCreate) SetNillableLabel(v *string) *AreaCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *AreaCreate) SetStartAt(v int) *AreaCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *AreaCreate) SetNillableStartAt(v *int) *AreaCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *AreaCreate) SetEndAt(v int) *AreaCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_c *AreaCreate) SetNillableEndAt(v *int) *AreaCreate {
	if v != nil {
		_c.SetEndAt(*v)
	}
	return _c
}

// SetReleaseConditionId2 sets the "release_condition_id2" field.
func (_c *AreaCreate) SetReleaseConditionId2(v int) *AreaCreate {
	_c.mutation.SetReleaseConditionId2(v)
	return _c
}

// SetNillableReleaseConditionId2 sets the "release_condition_id2" field if the given value is not nil.
func (_c *AreaCreate) SetNillableReleaseConditionId2(v *int) *AreaCreate {
	if v != nil {
		_c.SetReleaseConditionId2(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *AreaCreate) SetServerRegion(v string) *AreaCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the AreaMutation object of the builder.
func (_c *AreaCreate) Mutation() *AreaMutation {
	return _c.mutation
}

// Save creates the Area in the database.
func (_c *AreaCreate) Save(ctx context.Context) (*Area, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AreaCreate) SaveX(ctx context.Context) *Area {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AreaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AreaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AreaCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`sekai: missing required field "Area.game_id"`)}
	}
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Area.server_region"`)}
	}
	return nil
}

func (_c *AreaCreate) sqlSave(ctx context.Context) (*Area, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AreaCreate) createSpec() (*Area, *sqlgraph.CreateSpec) {
	var (
		_node = &Area{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(area.Table, sqlgraph.NewFieldSpec(area.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(area.FieldGameID, field.TypeInt, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.AssetbundleName(); ok {
		_spec.SetField(area.FieldAssetbundleName, field.TypeString, value)
		_node.AssetbundleName = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(area.FieldGroupID, field.TypeInt, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.IsBaseArea(); ok {
		_spec.SetField(area.FieldIsBaseArea, field.TypeBool, value)
		_node.IsBaseArea = value
	}
	if value, ok := _c.mutation.AreaType(); ok {
		_spec.SetField(area.FieldAreaType, field.TypeJSON, value)
		_node.AreaType = value
	}
	if value, ok := _c.mutation.ViewType(); ok {
		_spec.SetField(area.FieldViewType, field.TypeJSON, value)
		_node.ViewType = value
	}
	if value, ok := _c.mutation.DisplayTimelineType(); ok {
		_spec.SetField(area.FieldDisplayTimelineType, field.TypeJSON, value)
		_node.DisplayTimelineType = value
	}
	if value, ok := _c.mutation.AdditionalAreaType(); ok {
		_spec.SetField(area.FieldAdditionalAreaType, field.TypeJSON, value)
		_node.AdditionalAreaType = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(area.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ReleaseConditionID(); ok {
		_spec.SetField(area.FieldReleaseConditionID, field.TypeInt, value)
		_node.ReleaseConditionID = value
	}
	if value, ok := _c.mutation.SubName(); ok {
		_spec.SetField(area.FieldSubName, field.TypeString, value)
		_node.SubName = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(area.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(area.FieldStartAt, field.TypeInt, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(area.FieldEndAt, field.TypeInt, value)
		_node.EndAt = value
	}
	if value, ok := _c.mutation.ReleaseConditionId2(); ok {
		_spec.SetField(area.FieldReleaseConditionId2, field.TypeInt, value)
		_node.ReleaseConditionId2 = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(area.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// AreaCreateBulk is the builder for creating many Area entities in bulk.
type AreaCreateBulk struct {
	config
	err      error
	builders []*AreaCreate
}

// Save creates the Area entities in the database.
func (_c *AreaCreateBulk) Save(ctx context.Context) ([]*Area, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Area, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AreaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AreaCreateBulk) SaveX(ctx context.Context) []*Area {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AreaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AreaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
