// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"haruki-cloud/database/sekai/cardepisode"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardepisodeDelete is the builder for deleting a Cardepisode entity.
type CardepisodeDelete struct {
	config
	hooks    []Hook
	mutation *CardepisodeMutation
}

// Where appends a list predicates to the CardepisodeDelete builder.
func (_d *CardepisodeDelete) Where(ps ...predicate.Cardepisode) *CardepisodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CardepisodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardepisodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CardepisodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cardepisode.Table, sqlgraph.NewFieldSpec(cardepisode.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CardepisodeDeleteOne is the builder for deleting a single Cardepisode entity.
type CardepisodeDeleteOne struct {
	_d *CardepisodeDelete
}

// Where appends a list predicates to the CardepisodeDelete builder.
func (_d *CardepisodeDeleteOne) Where(ps ...predicate.Cardepisode) *CardepisodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CardepisodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cardepisode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardepisodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
