// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/challengelivehighscorereward"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChallengelivehighscorerewardCreate is the builder for creating a Challengelivehighscorereward entity.
type ChallengelivehighscorerewardCreate struct {
	config
	mutation *ChallengelivehighscorerewardMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *ChallengelivehighscorerewardCreate) SetGameID(v int64) *ChallengelivehighscorerewardCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *ChallengelivehighscorerewardCreate) SetCharacterID(v int64) *ChallengelivehighscorerewardCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_c *ChallengelivehighscorerewardCreate) SetNillableCharacterID(v *int64) *ChallengelivehighscorerewardCreate {
	if v != nil {
		_c.SetCharacterID(*v)
	}
	return _c
}

// SetHighScore sets the "high_score" field.
func (_c *ChallengelivehighscorerewardCreate) SetHighScore(v int64) *ChallengelivehighscorerewardCreate {
	_c.mutation.SetHighScore(v)
	return _c
}

// SetNillableHighScore sets the "high_score" field if the given value is not nil.
func (_c *ChallengelivehighscorerewardCreate) SetNillableHighScore(v *int64) *ChallengelivehighscorerewardCreate {
	if v != nil {
		_c.SetHighScore(*v)
	}
	return _c
}

// SetResourceBoxID sets the "resource_box_id" field.
func (_c *ChallengelivehighscorerewardCreate) SetResourceBoxID(v int64) *ChallengelivehighscorerewardCreate {
	_c.mutation.SetResourceBoxID(v)
	return _c
}

// SetNillableResourceBoxID sets the "resource_box_id" field if the given value is not nil.
func (_c *ChallengelivehighscorerewardCreate) SetNillableResourceBoxID(v *int64) *ChallengelivehighscorerewardCreate {
	if v != nil {
		_c.SetResourceBoxID(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *ChallengelivehighscorerewardCreate) SetServerRegion(v string) *ChallengelivehighscorerewardCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the ChallengelivehighscorerewardMutation object of the builder.
func (_c *ChallengelivehighscorerewardCreate) Mutation() *ChallengelivehighscorerewardMutation {
	return _c.mutation
}

// Save creates the Challengelivehighscorereward in the database.
func (_c *ChallengelivehighscorerewardCreate) Save(ctx context.Context) (*Challengelivehighscorereward, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChallengelivehighscorerewardCreate) SaveX(ctx context.Context) *Challengelivehighscorereward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChallengelivehighscorerewardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChallengelivehighscorerewardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChallengelivehighscorerewardCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`sekai: missing required field "Challengelivehighscorereward.game_id"`)}
	}
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Challengelivehighscorereward.server_region"`)}
	}
	return nil
}

func (_c *ChallengelivehighscorerewardCreate) sqlSave(ctx context.Context) (*Challengelivehighscorereward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChallengelivehighscorerewardCreate) createSpec() (*Challengelivehighscorereward, *sqlgraph.CreateSpec) {
	var (
		_node = &Challengelivehighscorereward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(challengelivehighscorereward.Table, sqlgraph.NewFieldSpec(challengelivehighscorereward.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(challengelivehighscorereward.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(challengelivehighscorereward.FieldCharacterID, field.TypeInt64, value)
		_node.CharacterID = value
	}
	if value, ok := _c.mutation.HighScore(); ok {
		_spec.SetField(challengelivehighscorereward.FieldHighScore, field.TypeInt64, value)
		_node.HighScore = value
	}
	if value, ok := _c.mutation.ResourceBoxID(); ok {
		_spec.SetField(challengelivehighscorereward.FieldResourceBoxID, field.TypeInt64, value)
		_node.ResourceBoxID = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(challengelivehighscorereward.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// ChallengelivehighscorerewardCreateBulk is the builder for creating many Challengelivehighscorereward entities in bulk.
type ChallengelivehighscorerewardCreateBulk struct {
	config
	err      error
	builders []*ChallengelivehighscorerewardCreate
}

// Save creates the Challengelivehighscorereward entities in the database.
func (_c *ChallengelivehighscorerewardCreateBulk) Save(ctx context.Context) ([]*Challengelivehighscorereward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Challengelivehighscorereward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChallengelivehighscorerewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChallengelivehighscorerewardCreateBulk) SaveX(ctx context.Context) []*Challengelivehighscorereward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChallengelivehighscorerewardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChallengelivehighscorerewardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
