// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/charactermissionv2areaitem"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Charactermissionv2AreaitemUpdate is the builder for updating Charactermissionv2Areaitem entities.
type Charactermissionv2AreaitemUpdate struct {
	config
	hooks    []Hook
	mutation *Charactermissionv2AreaitemMutation
}

// Where appends a list predicates to the Charactermissionv2AreaitemUpdate builder.
func (_u *Charactermissionv2AreaitemUpdate) Where(ps ...predicate.Charactermissionv2Areaitem) *Charactermissionv2AreaitemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdate) SetGameID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableGameID(v *int64) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdate) AddGameID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdate) ClearGameID() *Charactermissionv2AreaitemUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetCharacterMissionType sets the "character_mission_type" field.
func (_u *Charactermissionv2AreaitemUpdate) SetCharacterMissionType(v string) *Charactermissionv2AreaitemUpdate {
	_u.mutation.SetCharacterMissionType(v)
	return _u
}

// SetNillableCharacterMissionType sets the "character_mission_type" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableCharacterMissionType(v *string) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetCharacterMissionType(*v)
	}
	return _u
}

// ClearCharacterMissionType clears the value of the "character_mission_type" field.
func (_u *Charactermissionv2AreaitemUpdate) ClearCharacterMissionType() *Charactermissionv2AreaitemUpdate {
	_u.mutation.ClearCharacterMissionType()
	return _u
}

// SetAreaItemID sets the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdate) SetAreaItemID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.ResetAreaItemID()
	_u.mutation.SetAreaItemID(v)
	return _u
}

// SetNillableAreaItemID sets the "area_item_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableAreaItemID(v *int64) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetAreaItemID(*v)
	}
	return _u
}

// AddAreaItemID adds value to the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdate) AddAreaItemID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.AddAreaItemID(v)
	return _u
}

// ClearAreaItemID clears the value of the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdate) ClearAreaItemID() *Charactermissionv2AreaitemUpdate {
	_u.mutation.ClearAreaItemID()
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdate) SetCharacterID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.ResetCharacterID()
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableCharacterID(v *int64) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// AddCharacterID adds value to the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdate) AddCharacterID(v int64) *Charactermissionv2AreaitemUpdate {
	_u.mutation.AddCharacterID(v)
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdate) ClearCharacterID() *Charactermissionv2AreaitemUpdate {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetUnit sets the "unit" field.
func (_u *Charactermissionv2AreaitemUpdate) SetUnit(v string) *Charactermissionv2AreaitemUpdate {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableUnit(v *string) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// ClearUnit clears the value of the "unit" field.
func (_u *Charactermissionv2AreaitemUpdate) ClearUnit() *Charactermissionv2AreaitemUpdate {
	_u.mutation.ClearUnit()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *Charactermissionv2AreaitemUpdate) SetServerRegion(v string) *Charactermissionv2AreaitemUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdate) SetNillableServerRegion(v *string) *Charactermissionv2AreaitemUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the Charactermissionv2AreaitemMutation object of the builder.
func (_u *Charactermissionv2AreaitemUpdate) Mutation() *Charactermissionv2AreaitemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Charactermissionv2AreaitemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Charactermissionv2AreaitemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Charactermissionv2AreaitemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Charactermissionv2AreaitemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Charactermissionv2AreaitemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(charactermissionv2areaitem.Table, charactermissionv2areaitem.Columns, sqlgraph.NewFieldSpec(charactermissionv2areaitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CharacterMissionType(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldCharacterMissionType, field.TypeString, value)
	}
	if _u.mutation.CharacterMissionTypeCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldCharacterMissionType, field.TypeString)
	}
	if value, ok := _u.mutation.AreaItemID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAreaItemID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64, value)
	}
	if _u.mutation.AreaItemIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCharacterID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldUnit, field.TypeString, value)
	}
	if _u.mutation.UnitCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldUnit, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldServerRegion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{charactermissionv2areaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Charactermissionv2AreaitemUpdateOne is the builder for updating a single Charactermissionv2Areaitem entity.
type Charactermissionv2AreaitemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Charactermissionv2AreaitemMutation
}

// SetGameID sets the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetGameID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableGameID(v *int64) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) AddGameID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) ClearGameID() *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetCharacterMissionType sets the "character_mission_type" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetCharacterMissionType(v string) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.SetCharacterMissionType(v)
	return _u
}

// SetNillableCharacterMissionType sets the "character_mission_type" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableCharacterMissionType(v *string) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetCharacterMissionType(*v)
	}
	return _u
}

// ClearCharacterMissionType clears the value of the "character_mission_type" field.
func (_u *Charactermissionv2AreaitemUpdateOne) ClearCharacterMissionType() *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ClearCharacterMissionType()
	return _u
}

// SetAreaItemID sets the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetAreaItemID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ResetAreaItemID()
	_u.mutation.SetAreaItemID(v)
	return _u
}

// SetNillableAreaItemID sets the "area_item_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableAreaItemID(v *int64) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetAreaItemID(*v)
	}
	return _u
}

// AddAreaItemID adds value to the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) AddAreaItemID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.AddAreaItemID(v)
	return _u
}

// ClearAreaItemID clears the value of the "area_item_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) ClearAreaItemID() *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ClearAreaItemID()
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetCharacterID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ResetCharacterID()
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableCharacterID(v *int64) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// AddCharacterID adds value to the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) AddCharacterID(v int64) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.AddCharacterID(v)
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *Charactermissionv2AreaitemUpdateOne) ClearCharacterID() *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetUnit sets the "unit" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetUnit(v string) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableUnit(v *string) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// ClearUnit clears the value of the "unit" field.
func (_u *Charactermissionv2AreaitemUpdateOne) ClearUnit() *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.ClearUnit()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *Charactermissionv2AreaitemUpdateOne) SetServerRegion(v string) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *Charactermissionv2AreaitemUpdateOne) SetNillableServerRegion(v *string) *Charactermissionv2AreaitemUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the Charactermissionv2AreaitemMutation object of the builder.
func (_u *Charactermissionv2AreaitemUpdateOne) Mutation() *Charactermissionv2AreaitemMutation {
	return _u.mutation
}

// Where appends a list predicates to the Charactermissionv2AreaitemUpdate builder.
func (_u *Charactermissionv2AreaitemUpdateOne) Where(ps ...predicate.Charactermissionv2Areaitem) *Charactermissionv2AreaitemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Charactermissionv2AreaitemUpdateOne) Select(field string, fields ...string) *Charactermissionv2AreaitemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Charactermissionv2Areaitem entity.
func (_u *Charactermissionv2AreaitemUpdateOne) Save(ctx context.Context) (*Charactermissionv2Areaitem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Charactermissionv2AreaitemUpdateOne) SaveX(ctx context.Context) *Charactermissionv2Areaitem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Charactermissionv2AreaitemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Charactermissionv2AreaitemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Charactermissionv2AreaitemUpdateOne) sqlSave(ctx context.Context) (_node *Charactermissionv2Areaitem, err error) {
	_spec := sqlgraph.NewUpdateSpec(charactermissionv2areaitem.Table, charactermissionv2areaitem.Columns, sqlgraph.NewFieldSpec(charactermissionv2areaitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Charactermissionv2Areaitem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, charactermissionv2areaitem.FieldID)
		for _, f := range fields {
			if !charactermissionv2areaitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != charactermissionv2areaitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CharacterMissionType(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldCharacterMissionType, field.TypeString, value)
	}
	if _u.mutation.CharacterMissionTypeCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldCharacterMissionType, field.TypeString)
	}
	if value, ok := _u.mutation.AreaItemID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAreaItemID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64, value)
	}
	if _u.mutation.AreaItemIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldAreaItemID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCharacterID(); ok {
		_spec.AddField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldCharacterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldUnit, field.TypeString, value)
	}
	if _u.mutation.UnitCleared() {
		_spec.ClearField(charactermissionv2areaitem.FieldUnit, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(charactermissionv2areaitem.FieldServerRegion, field.TypeString, value)
	}
	_node = &Charactermissionv2Areaitem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{charactermissionv2areaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
