// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/charactermissionv2parametergroup"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// Charactermissionv2ParametergroupUpdate is the builder for updating Charactermissionv2Parametergroup entities.
type Charactermissionv2ParametergroupUpdate struct {
	config
	hooks    []Hook
	mutation *Charactermissionv2ParametergroupMutation
}

// Where appends a list predicates to the Charactermissionv2ParametergroupUpdate builder.
func (_u *Charactermissionv2ParametergroupUpdate) Where(ps ...predicate.Charactermissionv2Parametergroup) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetServerRegion(v string) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableServerRegion(v *string) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetGameID(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableGameID(v *int64) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdate) AddGameID(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdate) ClearGameID() *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetSeq sets the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetSeq(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableSeq(v *int64) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdate) AddSeq(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// ClearSeq clears the value of the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdate) ClearSeq() *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ClearSeq()
	return _u
}

// SetRequirement sets the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetRequirement(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ResetRequirement()
	_u.mutation.SetRequirement(v)
	return _u
}

// SetNillableRequirement sets the "requirement" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableRequirement(v *int64) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetRequirement(*v)
	}
	return _u
}

// AddRequirement adds value to the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdate) AddRequirement(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.AddRequirement(v)
	return _u
}

// ClearRequirement clears the value of the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdate) ClearRequirement() *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ClearRequirement()
	return _u
}

// SetExp sets the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetExp(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableExp(v *int64) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdate) AddExp(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.AddExp(v)
	return _u
}

// ClearExp clears the value of the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdate) ClearExp() *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ClearExp()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdate) SetQuantity(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdate) SetNillableQuantity(v *int64) *Charactermissionv2ParametergroupUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdate) AddQuantity(v int64) *Charactermissionv2ParametergroupUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// ClearQuantity clears the value of the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdate) ClearQuantity() *Charactermissionv2ParametergroupUpdate {
	_u.mutation.ClearQuantity()
	return _u
}

// Mutation returns the Charactermissionv2ParametergroupMutation object of the builder.
func (_u *Charactermissionv2ParametergroupUpdate) Mutation() *Charactermissionv2ParametergroupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Charactermissionv2ParametergroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Charactermissionv2ParametergroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Charactermissionv2ParametergroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Charactermissionv2ParametergroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Charactermissionv2ParametergroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(charactermissionv2parametergroup.Table, charactermissionv2parametergroup.Columns, sqlgraph.NewFieldSpec(charactermissionv2parametergroup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldServerRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64, value)
	}
	if _u.mutation.SeqCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64)
	}
	if value, ok := _u.mutation.Requirement(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequirement(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64, value)
	}
	if _u.mutation.RequirementCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldExp, field.TypeInt64, value)
	}
	if _u.mutation.ExpCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldExp, field.TypeInt64)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64, value)
	}
	if _u.mutation.QuantityCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{charactermissionv2parametergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Charactermissionv2ParametergroupUpdateOne is the builder for updating a single Charactermissionv2Parametergroup entity.
type Charactermissionv2ParametergroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Charactermissionv2ParametergroupMutation
}

// SetServerRegion sets the "server_region" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetServerRegion(v string) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableServerRegion(v *string) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetGameID(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableGameID(v *int64) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) AddGameID(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) ClearGameID() *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetSeq sets the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetSeq(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableSeq(v *int64) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) AddSeq(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// ClearSeq clears the value of the "seq" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) ClearSeq() *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ClearSeq()
	return _u
}

// SetRequirement sets the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetRequirement(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ResetRequirement()
	_u.mutation.SetRequirement(v)
	return _u
}

// SetNillableRequirement sets the "requirement" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableRequirement(v *int64) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetRequirement(*v)
	}
	return _u
}

// AddRequirement adds value to the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) AddRequirement(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.AddRequirement(v)
	return _u
}

// ClearRequirement clears the value of the "requirement" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) ClearRequirement() *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ClearRequirement()
	return _u
}

// SetExp sets the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetExp(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableExp(v *int64) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) AddExp(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.AddExp(v)
	return _u
}

// ClearExp clears the value of the "exp" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) ClearExp() *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ClearExp()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetQuantity(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *Charactermissionv2ParametergroupUpdateOne) SetNillableQuantity(v *int64) *Charactermissionv2ParametergroupUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) AddQuantity(v int64) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// ClearQuantity clears the value of the "quantity" field.
func (_u *Charactermissionv2ParametergroupUpdateOne) ClearQuantity() *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.ClearQuantity()
	return _u
}

// Mutation returns the Charactermissionv2ParametergroupMutation object of the builder.
func (_u *Charactermissionv2ParametergroupUpdateOne) Mutation() *Charactermissionv2ParametergroupMutation {
	return _u.mutation
}

// Where appends a list predicates to the Charactermissionv2ParametergroupUpdate builder.
func (_u *Charactermissionv2ParametergroupUpdateOne) Where(ps ...predicate.Charactermissionv2Parametergroup) *Charactermissionv2ParametergroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Charactermissionv2ParametergroupUpdateOne) Select(field string, fields ...string) *Charactermissionv2ParametergroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Charactermissionv2Parametergroup entity.
func (_u *Charactermissionv2ParametergroupUpdateOne) Save(ctx context.Context) (*Charactermissionv2Parametergroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Charactermissionv2ParametergroupUpdateOne) SaveX(ctx context.Context) *Charactermissionv2Parametergroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Charactermissionv2ParametergroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Charactermissionv2ParametergroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Charactermissionv2ParametergroupUpdateOne) sqlSave(ctx context.Context) (_node *Charactermissionv2Parametergroup, err error) {
	_spec := sqlgraph.NewUpdateSpec(charactermissionv2parametergroup.Table, charactermissionv2parametergroup.Columns, sqlgraph.NewFieldSpec(charactermissionv2parametergroup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Charactermissionv2Parametergroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, charactermissionv2parametergroup.FieldID)
		for _, f := range fields {
			if !charactermissionv2parametergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != charactermissionv2parametergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldServerRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64, value)
	}
	if _u.mutation.SeqCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldSeq, field.TypeInt64)
	}
	if value, ok := _u.mutation.Requirement(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequirement(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64, value)
	}
	if _u.mutation.RequirementCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldRequirement, field.TypeInt64)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldExp, field.TypeInt64, value)
	}
	if _u.mutation.ExpCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldExp, field.TypeInt64)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64, value)
	}
	if _u.mutation.QuantityCleared() {
		_spec.ClearField(charactermissionv2parametergroup.FieldQuantity, field.TypeInt64)
	}
	_node = &Charactermissionv2Parametergroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{charactermissionv2parametergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
