// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"haruki-cloud/database/sekai/customprofileshaperesource"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomprofileshaperesourceDelete is the builder for deleting a Customprofileshaperesource entity.
type CustomprofileshaperesourceDelete struct {
	config
	hooks    []Hook
	mutation *CustomprofileshaperesourceMutation
}

// Where appends a list predicates to the CustomprofileshaperesourceDelete builder.
func (_d *CustomprofileshaperesourceDelete) Where(ps ...predicate.Customprofileshaperesource) *CustomprofileshaperesourceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CustomprofileshaperesourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomprofileshaperesourceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CustomprofileshaperesourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(customprofileshaperesource.Table, sqlgraph.NewFieldSpec(customprofileshaperesource.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CustomprofileshaperesourceDeleteOne is the builder for deleting a single Customprofileshaperesource entity.
type CustomprofileshaperesourceDeleteOne struct {
	_d *CustomprofileshaperesourceDelete
}

// Where appends a list predicates to the CustomprofileshaperesourceDelete builder.
func (_d *CustomprofileshaperesourceDeleteOne) Where(ps ...predicate.Customprofileshaperesource) *CustomprofileshaperesourceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CustomprofileshaperesourceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{customprofileshaperesource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomprofileshaperesourceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
