// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"fmt"
	"haruki-cloud/database/sekai/eventcard"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Eventcard is the model entity for the Eventcard schema.
type Eventcard struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID int64 `json:"game_id,omitempty"`
	// CardID holds the value of the "card_id" field.
	CardID int64 `json:"card_id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID int64 `json:"event_id,omitempty"`
	// BonusRate holds the value of the "bonus_rate" field.
	BonusRate float64 `json:"bonus_rate,omitempty"`
	// LeaderBonusRate holds the value of the "leader_bonus_rate" field.
	LeaderBonusRate float64 `json:"leader_bonus_rate,omitempty"`
	// IsDisplayCardStory holds the value of the "is_display_card_story" field.
	IsDisplayCardStory bool `json:"is_display_card_story,omitempty"`
	// ServerRegion holds the value of the "server_region" field.
	ServerRegion string `json:"server_region,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Eventcard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventcard.FieldIsDisplayCardStory:
			values[i] = new(sql.NullBool)
		case eventcard.FieldBonusRate, eventcard.FieldLeaderBonusRate:
			values[i] = new(sql.NullFloat64)
		case eventcard.FieldID, eventcard.FieldGameID, eventcard.FieldCardID, eventcard.FieldEventID:
			values[i] = new(sql.NullInt64)
		case eventcard.FieldServerRegion:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Eventcard fields.
func (_m *Eventcard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventcard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case eventcard.FieldGameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = value.Int64
			}
		case eventcard.FieldCardID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field card_id", values[i])
			} else if value.Valid {
				_m.CardID = value.Int64
			}
		case eventcard.FieldEventID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.Int64
			}
		case eventcard.FieldBonusRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_rate", values[i])
			} else if value.Valid {
				_m.BonusRate = value.Float64
			}
		case eventcard.FieldLeaderBonusRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field leader_bonus_rate", values[i])
			} else if value.Valid {
				_m.LeaderBonusRate = value.Float64
			}
		case eventcard.FieldIsDisplayCardStory:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_display_card_story", values[i])
			} else if value.Valid {
				_m.IsDisplayCardStory = value.Bool
			}
		case eventcard.FieldServerRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_region", values[i])
			} else if value.Valid {
				_m.ServerRegion = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Eventcard.
// This includes values selected through modifiers, order, etc.
func (_m *Eventcard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Eventcard.
// Note that you need to call Eventcard.Unwrap() before calling this method if this Eventcard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Eventcard) Update() *EventcardUpdateOne {
	return NewEventcardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Eventcard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Eventcard) Unwrap() *Eventcard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("sekai: Eventcard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Eventcard) String() string {
	var builder strings.Builder
	builder.WriteString("Eventcard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("card_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CardID))
	builder.WriteString(", ")
	builder.WriteString("event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventID))
	builder.WriteString(", ")
	builder.WriteString("bonus_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusRate))
	builder.WriteString(", ")
	builder.WriteString("leader_bonus_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeaderBonusRate))
	builder.WriteString(", ")
	builder.WriteString("is_display_card_story=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDisplayCardStory))
	builder.WriteString(", ")
	builder.WriteString("server_region=")
	builder.WriteString(_m.ServerRegion)
	builder.WriteByte(')')
	return builder.String()
}

// Eventcards is a parsable slice of Eventcard.
type Eventcards []*Eventcard
