// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/eventexchangesummarie"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventexchangesummarieCreate is the builder for creating a Eventexchangesummarie entity.
type EventexchangesummarieCreate struct {
	config
	mutation *EventexchangesummarieMutation
	hooks    []Hook
}

// SetServerRegion sets the "server_region" field.
func (_c *EventexchangesummarieCreate) SetServerRegion(v string) *EventexchangesummarieCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// SetGameID sets the "game_id" field.
func (_c *EventexchangesummarieCreate) SetGameID(v int64) *EventexchangesummarieCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_c *EventexchangesummarieCreate) SetNillableGameID(v *int64) *EventexchangesummarieCreate {
	if v != nil {
		_c.SetGameID(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *EventexchangesummarieCreate) SetEventID(v int64) *EventexchangesummarieCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_c *EventexchangesummarieCreate) SetNillableEventID(v *int64) *EventexchangesummarieCreate {
	if v != nil {
		_c.SetEventID(*v)
	}
	return _c
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_c *EventexchangesummarieCreate) SetAssetbundleName(v string) *EventexchangesummarieCreate {
	_c.mutation.SetAssetbundleName(v)
	return _c
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_c *EventexchangesummarieCreate) SetNillableAssetbundleName(v *string) *EventexchangesummarieCreate {
	if v != nil {
		_c.SetAssetbundleName(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *EventexchangesummarieCreate) SetStartAt(v int64) *EventexchangesummarieCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *EventexchangesummarieCreate) SetNillableStartAt(v *int64) *EventexchangesummarieCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *EventexchangesummarieCreate) SetEndAt(v int64) *EventexchangesummarieCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_c *EventexchangesummarieCreate) SetNillableEndAt(v *int64) *EventexchangesummarieCreate {
	if v != nil {
		_c.SetEndAt(*v)
	}
	return _c
}

// SetEventExchanges sets the "event_exchanges" field.
func (_c *EventexchangesummarieCreate) SetEventExchanges(v []interface{}) *EventexchangesummarieCreate {
	_c.mutation.SetEventExchanges(v)
	return _c
}

// Mutation returns the EventexchangesummarieMutation object of the builder.
func (_c *EventexchangesummarieCreate) Mutation() *EventexchangesummarieMutation {
	return _c.mutation
}

// Save creates the Eventexchangesummarie in the database.
func (_c *EventexchangesummarieCreate) Save(ctx context.Context) (*Eventexchangesummarie, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventexchangesummarieCreate) SaveX(ctx context.Context) *Eventexchangesummarie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventexchangesummarieCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventexchangesummarieCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventexchangesummarieCreate) check() error {
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Eventexchangesummarie.server_region"`)}
	}
	return nil
}

func (_c *EventexchangesummarieCreate) sqlSave(ctx context.Context) (*Eventexchangesummarie, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventexchangesummarieCreate) createSpec() (*Eventexchangesummarie, *sqlgraph.CreateSpec) {
	var (
		_node = &Eventexchangesummarie{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventexchangesummarie.Table, sqlgraph.NewFieldSpec(eventexchangesummarie.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(eventexchangesummarie.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(eventexchangesummarie.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(eventexchangesummarie.FieldEventID, field.TypeInt64, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.AssetbundleName(); ok {
		_spec.SetField(eventexchangesummarie.FieldAssetbundleName, field.TypeString, value)
		_node.AssetbundleName = value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(eventexchangesummarie.FieldStartAt, field.TypeInt64, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(eventexchangesummarie.FieldEndAt, field.TypeInt64, value)
		_node.EndAt = value
	}
	if value, ok := _c.mutation.EventExchanges(); ok {
		_spec.SetField(eventexchangesummarie.FieldEventExchanges, field.TypeJSON, value)
		_node.EventExchanges = value
	}
	return _node, _spec
}

// EventexchangesummarieCreateBulk is the builder for creating many Eventexchangesummarie entities in bulk.
type EventexchangesummarieCreateBulk struct {
	config
	err      error
	builders []*EventexchangesummarieCreate
}

// Save creates the Eventexchangesummarie entities in the database.
func (_c *EventexchangesummarieCreateBulk) Save(ctx context.Context) ([]*Eventexchangesummarie, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Eventexchangesummarie, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventexchangesummarieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventexchangesummarieCreateBulk) SaveX(ctx context.Context) []*Eventexchangesummarie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventexchangesummarieCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventexchangesummarieCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
