// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"haruki-cloud/database/sekai/gachaceilitem"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GachaceilitemDelete is the builder for deleting a Gachaceilitem entity.
type GachaceilitemDelete struct {
	config
	hooks    []Hook
	mutation *GachaceilitemMutation
}

// Where appends a list predicates to the GachaceilitemDelete builder.
func (_d *GachaceilitemDelete) Where(ps ...predicate.Gachaceilitem) *GachaceilitemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GachaceilitemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GachaceilitemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GachaceilitemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gachaceilitem.Table, sqlgraph.NewFieldSpec(gachaceilitem.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GachaceilitemDeleteOne is the builder for deleting a single Gachaceilitem entity.
type GachaceilitemDeleteOne struct {
	_d *GachaceilitemDelete
}

// Where appends a list predicates to the GachaceilitemDelete builder.
func (_d *GachaceilitemDeleteOne) Where(ps ...predicate.Gachaceilitem) *GachaceilitemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GachaceilitemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gachaceilitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GachaceilitemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
