// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/gamecharacterunit"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// GamecharacterunitUpdate is the builder for updating Gamecharacterunit entities.
type GamecharacterunitUpdate struct {
	config
	hooks    []Hook
	mutation *GamecharacterunitMutation
}

// Where appends a list predicates to the GamecharacterunitUpdate builder.
func (_u *GamecharacterunitUpdate) Where(ps ...predicate.Gamecharacterunit) *GamecharacterunitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *GamecharacterunitUpdate) SetGameID(v int64) *GamecharacterunitUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *GamecharacterunitUpdate) SetNillableGameID(v *int64) *GamecharacterunitUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *GamecharacterunitUpdate) AddGameID(v int64) *GamecharacterunitUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// SetGameCharacterID sets the "game_character_id" field.
func (_u *GamecharacterunitUpdate) SetGameCharacterID(v int64) *GamecharacterunitUpdate {
	_u.mutation.ResetGameCharacterID()
	_u.mutation.SetGameCharacterID(v)
	return _u
}

// SetNillableGameCharacterID sets the "game_character_id" field if the given value is not nil.
func (_u *GamecharacterunitUpdate) SetNillableGameCharacterID(v *int64) *GamecharacterunitUpdate {
	if v != nil {
		_u.SetGameCharacterID(*v)
	}
	return _u
}

// AddGameCharacterID adds value to the "game_character_id" field.
func (_u *GamecharacterunitUpdate) AddGameCharacterID(v int64) *GamecharacterunitUpdate {
	_u.mutation.AddGameCharacterID(v)
	return _u
}

// ClearGameCharacterID clears the value of the "game_character_id" field.
func (_u *GamecharacterunitUpdate) ClearGameCharacterID() *GamecharacterunitUpdate {
	_u.mutation.ClearGameCharacterID()
	return _u
}

// SetUnit sets the "unit" field.
func (_u *GamecharacterunitUpdate) SetUnit(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.SetUnit(v)
	return _u
}

// AppendUnit appends value to the "unit" field.
func (_u *GamecharacterunitUpdate) AppendUnit(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.AppendUnit(v)
	return _u
}

// ClearUnit clears the value of the "unit" field.
func (_u *GamecharacterunitUpdate) ClearUnit() *GamecharacterunitUpdate {
	_u.mutation.ClearUnit()
	return _u
}

// SetColorCode sets the "color_code" field.
func (_u *GamecharacterunitUpdate) SetColorCode(v string) *GamecharacterunitUpdate {
	_u.mutation.SetColorCode(v)
	return _u
}

// SetNillableColorCode sets the "color_code" field if the given value is not nil.
func (_u *GamecharacterunitUpdate) SetNillableColorCode(v *string) *GamecharacterunitUpdate {
	if v != nil {
		_u.SetColorCode(*v)
	}
	return _u
}

// ClearColorCode clears the value of the "color_code" field.
func (_u *GamecharacterunitUpdate) ClearColorCode() *GamecharacterunitUpdate {
	_u.mutation.ClearColorCode()
	return _u
}

// SetSkinColorCode sets the "skin_color_code" field.
func (_u *GamecharacterunitUpdate) SetSkinColorCode(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.SetSkinColorCode(v)
	return _u
}

// AppendSkinColorCode appends value to the "skin_color_code" field.
func (_u *GamecharacterunitUpdate) AppendSkinColorCode(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.AppendSkinColorCode(v)
	return _u
}

// ClearSkinColorCode clears the value of the "skin_color_code" field.
func (_u *GamecharacterunitUpdate) ClearSkinColorCode() *GamecharacterunitUpdate {
	_u.mutation.ClearSkinColorCode()
	return _u
}

// SetSkinShadowColorCode1 sets the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdate) SetSkinShadowColorCode1(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.SetSkinShadowColorCode1(v)
	return _u
}

// AppendSkinShadowColorCode1 appends value to the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdate) AppendSkinShadowColorCode1(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.AppendSkinShadowColorCode1(v)
	return _u
}

// ClearSkinShadowColorCode1 clears the value of the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdate) ClearSkinShadowColorCode1() *GamecharacterunitUpdate {
	_u.mutation.ClearSkinShadowColorCode1()
	return _u
}

// SetSkinShadowColorCode2 sets the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdate) SetSkinShadowColorCode2(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.SetSkinShadowColorCode2(v)
	return _u
}

// AppendSkinShadowColorCode2 appends value to the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdate) AppendSkinShadowColorCode2(v json.RawMessage) *GamecharacterunitUpdate {
	_u.mutation.AppendSkinShadowColorCode2(v)
	return _u
}

// ClearSkinShadowColorCode2 clears the value of the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdate) ClearSkinShadowColorCode2() *GamecharacterunitUpdate {
	_u.mutation.ClearSkinShadowColorCode2()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *GamecharacterunitUpdate) SetServerRegion(v string) *GamecharacterunitUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *GamecharacterunitUpdate) SetNillableServerRegion(v *string) *GamecharacterunitUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the GamecharacterunitMutation object of the builder.
func (_u *GamecharacterunitUpdate) Mutation() *GamecharacterunitMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GamecharacterunitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GamecharacterunitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GamecharacterunitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GamecharacterunitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GamecharacterunitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gamecharacterunit.Table, gamecharacterunit.Columns, sqlgraph.NewFieldSpec(gamecharacterunit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(gamecharacterunit.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(gamecharacterunit.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GameCharacterID(); ok {
		_spec.SetField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameCharacterID(); ok {
		_spec.AddField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64, value)
	}
	if _u.mutation.GameCharacterIDCleared() {
		_spec.ClearField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(gamecharacterunit.FieldUnit, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUnit(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldUnit, value)
		})
	}
	if _u.mutation.UnitCleared() {
		_spec.ClearField(gamecharacterunit.FieldUnit, field.TypeJSON)
	}
	if value, ok := _u.mutation.ColorCode(); ok {
		_spec.SetField(gamecharacterunit.FieldColorCode, field.TypeString, value)
	}
	if _u.mutation.ColorCodeCleared() {
		_spec.ClearField(gamecharacterunit.FieldColorCode, field.TypeString)
	}
	if value, ok := _u.mutation.SkinColorCode(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinColorCode, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinColorCode(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinColorCode, value)
		})
	}
	if _u.mutation.SkinColorCodeCleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinColorCode, field.TypeJSON)
	}
	if value, ok := _u.mutation.SkinShadowColorCode1(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinShadowColorCode1, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinShadowColorCode1(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinShadowColorCode1, value)
		})
	}
	if _u.mutation.SkinShadowColorCode1Cleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinShadowColorCode1, field.TypeJSON)
	}
	if value, ok := _u.mutation.SkinShadowColorCode2(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinShadowColorCode2, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinShadowColorCode2(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinShadowColorCode2, value)
		})
	}
	if _u.mutation.SkinShadowColorCode2Cleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinShadowColorCode2, field.TypeJSON)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(gamecharacterunit.FieldServerRegion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamecharacterunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GamecharacterunitUpdateOne is the builder for updating a single Gamecharacterunit entity.
type GamecharacterunitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GamecharacterunitMutation
}

// SetGameID sets the "game_id" field.
func (_u *GamecharacterunitUpdateOne) SetGameID(v int64) *GamecharacterunitUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *GamecharacterunitUpdateOne) SetNillableGameID(v *int64) *GamecharacterunitUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *GamecharacterunitUpdateOne) AddGameID(v int64) *GamecharacterunitUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// SetGameCharacterID sets the "game_character_id" field.
func (_u *GamecharacterunitUpdateOne) SetGameCharacterID(v int64) *GamecharacterunitUpdateOne {
	_u.mutation.ResetGameCharacterID()
	_u.mutation.SetGameCharacterID(v)
	return _u
}

// SetNillableGameCharacterID sets the "game_character_id" field if the given value is not nil.
func (_u *GamecharacterunitUpdateOne) SetNillableGameCharacterID(v *int64) *GamecharacterunitUpdateOne {
	if v != nil {
		_u.SetGameCharacterID(*v)
	}
	return _u
}

// AddGameCharacterID adds value to the "game_character_id" field.
func (_u *GamecharacterunitUpdateOne) AddGameCharacterID(v int64) *GamecharacterunitUpdateOne {
	_u.mutation.AddGameCharacterID(v)
	return _u
}

// ClearGameCharacterID clears the value of the "game_character_id" field.
func (_u *GamecharacterunitUpdateOne) ClearGameCharacterID() *GamecharacterunitUpdateOne {
	_u.mutation.ClearGameCharacterID()
	return _u
}

// SetUnit sets the "unit" field.
func (_u *GamecharacterunitUpdateOne) SetUnit(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.SetUnit(v)
	return _u
}

// AppendUnit appends value to the "unit" field.
func (_u *GamecharacterunitUpdateOne) AppendUnit(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.AppendUnit(v)
	return _u
}

// ClearUnit clears the value of the "unit" field.
func (_u *GamecharacterunitUpdateOne) ClearUnit() *GamecharacterunitUpdateOne {
	_u.mutation.ClearUnit()
	return _u
}

// SetColorCode sets the "color_code" field.
func (_u *GamecharacterunitUpdateOne) SetColorCode(v string) *GamecharacterunitUpdateOne {
	_u.mutation.SetColorCode(v)
	return _u
}

// SetNillableColorCode sets the "color_code" field if the given value is not nil.
func (_u *GamecharacterunitUpdateOne) SetNillableColorCode(v *string) *GamecharacterunitUpdateOne {
	if v != nil {
		_u.SetColorCode(*v)
	}
	return _u
}

// ClearColorCode clears the value of the "color_code" field.
func (_u *GamecharacterunitUpdateOne) ClearColorCode() *GamecharacterunitUpdateOne {
	_u.mutation.ClearColorCode()
	return _u
}

// SetSkinColorCode sets the "skin_color_code" field.
func (_u *GamecharacterunitUpdateOne) SetSkinColorCode(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.SetSkinColorCode(v)
	return _u
}

// AppendSkinColorCode appends value to the "skin_color_code" field.
func (_u *GamecharacterunitUpdateOne) AppendSkinColorCode(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.AppendSkinColorCode(v)
	return _u
}

// ClearSkinColorCode clears the value of the "skin_color_code" field.
func (_u *GamecharacterunitUpdateOne) ClearSkinColorCode() *GamecharacterunitUpdateOne {
	_u.mutation.ClearSkinColorCode()
	return _u
}

// SetSkinShadowColorCode1 sets the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdateOne) SetSkinShadowColorCode1(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.SetSkinShadowColorCode1(v)
	return _u
}

// AppendSkinShadowColorCode1 appends value to the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdateOne) AppendSkinShadowColorCode1(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.AppendSkinShadowColorCode1(v)
	return _u
}

// ClearSkinShadowColorCode1 clears the value of the "skin_shadow_color_code1" field.
func (_u *GamecharacterunitUpdateOne) ClearSkinShadowColorCode1() *GamecharacterunitUpdateOne {
	_u.mutation.ClearSkinShadowColorCode1()
	return _u
}

// SetSkinShadowColorCode2 sets the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdateOne) SetSkinShadowColorCode2(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.SetSkinShadowColorCode2(v)
	return _u
}

// AppendSkinShadowColorCode2 appends value to the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdateOne) AppendSkinShadowColorCode2(v json.RawMessage) *GamecharacterunitUpdateOne {
	_u.mutation.AppendSkinShadowColorCode2(v)
	return _u
}

// ClearSkinShadowColorCode2 clears the value of the "skin_shadow_color_code2" field.
func (_u *GamecharacterunitUpdateOne) ClearSkinShadowColorCode2() *GamecharacterunitUpdateOne {
	_u.mutation.ClearSkinShadowColorCode2()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *GamecharacterunitUpdateOne) SetServerRegion(v string) *GamecharacterunitUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *GamecharacterunitUpdateOne) SetNillableServerRegion(v *string) *GamecharacterunitUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the GamecharacterunitMutation object of the builder.
func (_u *GamecharacterunitUpdateOne) Mutation() *GamecharacterunitMutation {
	return _u.mutation
}

// Where appends a list predicates to the GamecharacterunitUpdate builder.
func (_u *GamecharacterunitUpdateOne) Where(ps ...predicate.Gamecharacterunit) *GamecharacterunitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GamecharacterunitUpdateOne) Select(field string, fields ...string) *GamecharacterunitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Gamecharacterunit entity.
func (_u *GamecharacterunitUpdateOne) Save(ctx context.Context) (*Gamecharacterunit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GamecharacterunitUpdateOne) SaveX(ctx context.Context) *Gamecharacterunit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GamecharacterunitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GamecharacterunitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GamecharacterunitUpdateOne) sqlSave(ctx context.Context) (_node *Gamecharacterunit, err error) {
	_spec := sqlgraph.NewUpdateSpec(gamecharacterunit.Table, gamecharacterunit.Columns, sqlgraph.NewFieldSpec(gamecharacterunit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Gamecharacterunit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamecharacterunit.FieldID)
		for _, f := range fields {
			if !gamecharacterunit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != gamecharacterunit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(gamecharacterunit.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(gamecharacterunit.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GameCharacterID(); ok {
		_spec.SetField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameCharacterID(); ok {
		_spec.AddField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64, value)
	}
	if _u.mutation.GameCharacterIDCleared() {
		_spec.ClearField(gamecharacterunit.FieldGameCharacterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(gamecharacterunit.FieldUnit, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUnit(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldUnit, value)
		})
	}
	if _u.mutation.UnitCleared() {
		_spec.ClearField(gamecharacterunit.FieldUnit, field.TypeJSON)
	}
	if value, ok := _u.mutation.ColorCode(); ok {
		_spec.SetField(gamecharacterunit.FieldColorCode, field.TypeString, value)
	}
	if _u.mutation.ColorCodeCleared() {
		_spec.ClearField(gamecharacterunit.FieldColorCode, field.TypeString)
	}
	if value, ok := _u.mutation.SkinColorCode(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinColorCode, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinColorCode(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinColorCode, value)
		})
	}
	if _u.mutation.SkinColorCodeCleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinColorCode, field.TypeJSON)
	}
	if value, ok := _u.mutation.SkinShadowColorCode1(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinShadowColorCode1, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinShadowColorCode1(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinShadowColorCode1, value)
		})
	}
	if _u.mutation.SkinShadowColorCode1Cleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinShadowColorCode1, field.TypeJSON)
	}
	if value, ok := _u.mutation.SkinShadowColorCode2(); ok {
		_spec.SetField(gamecharacterunit.FieldSkinShadowColorCode2, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkinShadowColorCode2(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gamecharacterunit.FieldSkinShadowColorCode2, value)
		})
	}
	if _u.mutation.SkinShadowColorCode2Cleared() {
		_spec.ClearField(gamecharacterunit.FieldSkinShadowColorCode2, field.TypeJSON)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(gamecharacterunit.FieldServerRegion, field.TypeString, value)
	}
	_node = &Gamecharacterunit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamecharacterunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
