// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/gamecharacter"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GamecharacterCreate is the builder for creating a Gamecharacter entity.
type GamecharacterCreate struct {
	config
	mutation *GamecharacterMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *GamecharacterCreate) SetGameID(v int64) *GamecharacterCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableGameID(v *int64) *GamecharacterCreate {
	if v != nil {
		_c.SetGameID(*v)
	}
	return _c
}

// SetSeq sets the "seq" field.
func (_c *GamecharacterCreate) SetSeq(v int64) *GamecharacterCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableSeq(v *int64) *GamecharacterCreate {
	if v != nil {
		_c.SetSeq(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *GamecharacterCreate) SetResourceID(v int64) *GamecharacterCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableResourceID(v *int64) *GamecharacterCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetFirstName sets the "first_name" field.
func (_c *GamecharacterCreate) SetFirstName(v string) *GamecharacterCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableFirstName(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetFirstName(*v)
	}
	return _c
}

// SetGivenName sets the "given_name" field.
func (_c *GamecharacterCreate) SetGivenName(v string) *GamecharacterCreate {
	_c.mutation.SetGivenName(v)
	return _c
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableGivenName(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetGivenName(*v)
	}
	return _c
}

// SetFirstNameRuby sets the "first_name_ruby" field.
func (_c *GamecharacterCreate) SetFirstNameRuby(v string) *GamecharacterCreate {
	_c.mutation.SetFirstNameRuby(v)
	return _c
}

// SetNillableFirstNameRuby sets the "first_name_ruby" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableFirstNameRuby(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetFirstNameRuby(*v)
	}
	return _c
}

// SetGivenNameRuby sets the "given_name_ruby" field.
func (_c *GamecharacterCreate) SetGivenNameRuby(v string) *GamecharacterCreate {
	_c.mutation.SetGivenNameRuby(v)
	return _c
}

// SetNillableGivenNameRuby sets the "given_name_ruby" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableGivenNameRuby(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetGivenNameRuby(*v)
	}
	return _c
}

// SetFirstNameEnglish sets the "first_name_english" field.
func (_c *GamecharacterCreate) SetFirstNameEnglish(v string) *GamecharacterCreate {
	_c.mutation.SetFirstNameEnglish(v)
	return _c
}

// SetNillableFirstNameEnglish sets the "first_name_english" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableFirstNameEnglish(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetFirstNameEnglish(*v)
	}
	return _c
}

// SetGivenNameEnglish sets the "given_name_english" field.
func (_c *GamecharacterCreate) SetGivenNameEnglish(v string) *GamecharacterCreate {
	_c.mutation.SetGivenNameEnglish(v)
	return _c
}

// SetNillableGivenNameEnglish sets the "given_name_english" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableGivenNameEnglish(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetGivenNameEnglish(*v)
	}
	return _c
}

// SetGender sets the "gender" field.
func (_c *GamecharacterCreate) SetGender(v string) *GamecharacterCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableGender(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *GamecharacterCreate) SetHeight(v float64) *GamecharacterCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableHeight(v *float64) *GamecharacterCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetLive2DHeightAdjustment sets the "live2_d_height_adjustment" field.
func (_c *GamecharacterCreate) SetLive2DHeightAdjustment(v float64) *GamecharacterCreate {
	_c.mutation.SetLive2DHeightAdjustment(v)
	return _c
}

// SetNillableLive2DHeightAdjustment sets the "live2_d_height_adjustment" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableLive2DHeightAdjustment(v *float64) *GamecharacterCreate {
	if v != nil {
		_c.SetLive2DHeightAdjustment(*v)
	}
	return _c
}

// SetFigure sets the "figure" field.
func (_c *GamecharacterCreate) SetFigure(v string) *GamecharacterCreate {
	_c.mutation.SetFigure(v)
	return _c
}

// SetNillableFigure sets the "figure" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableFigure(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetFigure(*v)
	}
	return _c
}

// SetBreastSize sets the "breast_size" field.
func (_c *GamecharacterCreate) SetBreastSize(v string) *GamecharacterCreate {
	_c.mutation.SetBreastSize(v)
	return _c
}

// SetNillableBreastSize sets the "breast_size" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableBreastSize(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetBreastSize(*v)
	}
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *GamecharacterCreate) SetModelName(v string) *GamecharacterCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableModelName(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetModelName(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *GamecharacterCreate) SetUnit(v string) *GamecharacterCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableUnit(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetUnit(*v)
	}
	return _c
}

// SetSupportUnitType sets the "support_unit_type" field.
func (_c *GamecharacterCreate) SetSupportUnitType(v string) *GamecharacterCreate {
	_c.mutation.SetSupportUnitType(v)
	return _c
}

// SetNillableSupportUnitType sets the "support_unit_type" field if the given value is not nil.
func (_c *GamecharacterCreate) SetNillableSupportUnitType(v *string) *GamecharacterCreate {
	if v != nil {
		_c.SetSupportUnitType(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *GamecharacterCreate) SetServerRegion(v string) *GamecharacterCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the GamecharacterMutation object of the builder.
func (_c *GamecharacterCreate) Mutation() *GamecharacterMutation {
	return _c.mutation
}

// Save creates the Gamecharacter in the database.
func (_c *GamecharacterCreate) Save(ctx context.Context) (*Gamecharacter, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GamecharacterCreate) SaveX(ctx context.Context) *Gamecharacter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GamecharacterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GamecharacterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GamecharacterCreate) check() error {
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Gamecharacter.server_region"`)}
	}
	return nil
}

func (_c *GamecharacterCreate) sqlSave(ctx context.Context) (*Gamecharacter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GamecharacterCreate) createSpec() (*Gamecharacter, *sqlgraph.CreateSpec) {
	var (
		_node = &Gamecharacter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gamecharacter.Table, sqlgraph.NewFieldSpec(gamecharacter.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(gamecharacter.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(gamecharacter.FieldSeq, field.TypeInt64, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(gamecharacter.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(gamecharacter.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.GivenName(); ok {
		_spec.SetField(gamecharacter.FieldGivenName, field.TypeString, value)
		_node.GivenName = value
	}
	if value, ok := _c.mutation.FirstNameRuby(); ok {
		_spec.SetField(gamecharacter.FieldFirstNameRuby, field.TypeString, value)
		_node.FirstNameRuby = value
	}
	if value, ok := _c.mutation.GivenNameRuby(); ok {
		_spec.SetField(gamecharacter.FieldGivenNameRuby, field.TypeString, value)
		_node.GivenNameRuby = value
	}
	if value, ok := _c.mutation.FirstNameEnglish(); ok {
		_spec.SetField(gamecharacter.FieldFirstNameEnglish, field.TypeString, value)
		_node.FirstNameEnglish = value
	}
	if value, ok := _c.mutation.GivenNameEnglish(); ok {
		_spec.SetField(gamecharacter.FieldGivenNameEnglish, field.TypeString, value)
		_node.GivenNameEnglish = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(gamecharacter.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(gamecharacter.FieldHeight, field.TypeFloat64, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Live2DHeightAdjustment(); ok {
		_spec.SetField(gamecharacter.FieldLive2DHeightAdjustment, field.TypeFloat64, value)
		_node.Live2DHeightAdjustment = value
	}
	if value, ok := _c.mutation.Figure(); ok {
		_spec.SetField(gamecharacter.FieldFigure, field.TypeString, value)
		_node.Figure = value
	}
	if value, ok := _c.mutation.BreastSize(); ok {
		_spec.SetField(gamecharacter.FieldBreastSize, field.TypeString, value)
		_node.BreastSize = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(gamecharacter.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(gamecharacter.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.SupportUnitType(); ok {
		_spec.SetField(gamecharacter.FieldSupportUnitType, field.TypeString, value)
		_node.SupportUnitType = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(gamecharacter.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// GamecharacterCreateBulk is the builder for creating many Gamecharacter entities in bulk.
type GamecharacterCreateBulk struct {
	config
	err      error
	builders []*GamecharacterCreate
}

// Save creates the Gamecharacter entities in the database.
func (_c *GamecharacterCreateBulk) Save(ctx context.Context) ([]*Gamecharacter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Gamecharacter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GamecharacterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GamecharacterCreateBulk) SaveX(ctx context.Context) []*Gamecharacter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GamecharacterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GamecharacterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
