// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/honorgroup"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HonorgroupCreate is the builder for creating a Honorgroup entity.
type HonorgroupCreate struct {
	config
	mutation *HonorgroupMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *HonorgroupCreate) SetGameID(v int64) *HonorgroupCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_c *HonorgroupCreate) SetNillableGameID(v *int64) *HonorgroupCreate {
	if v != nil {
		_c.SetGameID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *HonorgroupCreate) SetName(v string) *HonorgroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *HonorgroupCreate) SetNillableName(v *string) *HonorgroupCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetPronunciation sets the "pronunciation" field.
func (_c *HonorgroupCreate) SetPronunciation(v string) *HonorgroupCreate {
	_c.mutation.SetPronunciation(v)
	return _c
}

// SetNillablePronunciation sets the "pronunciation" field if the given value is not nil.
func (_c *HonorgroupCreate) SetNillablePronunciation(v *string) *HonorgroupCreate {
	if v != nil {
		_c.SetPronunciation(*v)
	}
	return _c
}

// SetHonorType sets the "honor_type" field.
func (_c *HonorgroupCreate) SetHonorType(v json.RawMessage) *HonorgroupCreate {
	_c.mutation.SetHonorType(v)
	return _c
}

// SetBackgroundAssetbundleName sets the "background_assetbundle_name" field.
func (_c *HonorgroupCreate) SetBackgroundAssetbundleName(v string) *HonorgroupCreate {
	_c.mutation.SetBackgroundAssetbundleName(v)
	return _c
}

// SetNillableBackgroundAssetbundleName sets the "background_assetbundle_name" field if the given value is not nil.
func (_c *HonorgroupCreate) SetNillableBackgroundAssetbundleName(v *string) *HonorgroupCreate {
	if v != nil {
		_c.SetBackgroundAssetbundleName(*v)
	}
	return _c
}

// SetFrameName sets the "frame_name" field.
func (_c *HonorgroupCreate) SetFrameName(v string) *HonorgroupCreate {
	_c.mutation.SetFrameName(v)
	return _c
}

// SetNillableFrameName sets the "frame_name" field if the given value is not nil.
func (_c *HonorgroupCreate) SetNillableFrameName(v *string) *HonorgroupCreate {
	if v != nil {
		_c.SetFrameName(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *HonorgroupCreate) SetServerRegion(v string) *HonorgroupCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the HonorgroupMutation object of the builder.
func (_c *HonorgroupCreate) Mutation() *HonorgroupMutation {
	return _c.mutation
}

// Save creates the Honorgroup in the database.
func (_c *HonorgroupCreate) Save(ctx context.Context) (*Honorgroup, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HonorgroupCreate) SaveX(ctx context.Context) *Honorgroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HonorgroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HonorgroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HonorgroupCreate) check() error {
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Honorgroup.server_region"`)}
	}
	return nil
}

func (_c *HonorgroupCreate) sqlSave(ctx context.Context) (*Honorgroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HonorgroupCreate) createSpec() (*Honorgroup, *sqlgraph.CreateSpec) {
	var (
		_node = &Honorgroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(honorgroup.Table, sqlgraph.NewFieldSpec(honorgroup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(honorgroup.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(honorgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Pronunciation(); ok {
		_spec.SetField(honorgroup.FieldPronunciation, field.TypeString, value)
		_node.Pronunciation = value
	}
	if value, ok := _c.mutation.HonorType(); ok {
		_spec.SetField(honorgroup.FieldHonorType, field.TypeJSON, value)
		_node.HonorType = value
	}
	if value, ok := _c.mutation.BackgroundAssetbundleName(); ok {
		_spec.SetField(honorgroup.FieldBackgroundAssetbundleName, field.TypeString, value)
		_node.BackgroundAssetbundleName = value
	}
	if value, ok := _c.mutation.FrameName(); ok {
		_spec.SetField(honorgroup.FieldFrameName, field.TypeString, value)
		_node.FrameName = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(honorgroup.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// HonorgroupCreateBulk is the builder for creating many Honorgroup entities in bulk.
type HonorgroupCreateBulk struct {
	config
	err      error
	builders []*HonorgroupCreate
}

// Save creates the Honorgroup entities in the database.
func (_c *HonorgroupCreateBulk) Save(ctx context.Context) ([]*Honorgroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Honorgroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HonorgroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HonorgroupCreateBulk) SaveX(ctx context.Context) []*Honorgroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HonorgroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HonorgroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
