// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/level"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LevelUpdate is the builder for updating Level entities.
type LevelUpdate struct {
	config
	hooks    []Hook
	mutation *LevelMutation
}

// Where appends a list predicates to the LevelUpdate builder.
func (_u *LevelUpdate) Where(ps ...predicate.Level) *LevelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *LevelUpdate) SetGameID(v int64) *LevelUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableGameID(v *int64) *LevelUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *LevelUpdate) AddGameID(v int64) *LevelUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *LevelUpdate) ClearGameID() *LevelUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetLevelType sets the "level_type" field.
func (_u *LevelUpdate) SetLevelType(v string) *LevelUpdate {
	_u.mutation.SetLevelType(v)
	return _u
}

// SetNillableLevelType sets the "level_type" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableLevelType(v *string) *LevelUpdate {
	if v != nil {
		_u.SetLevelType(*v)
	}
	return _u
}

// ClearLevelType clears the value of the "level_type" field.
func (_u *LevelUpdate) ClearLevelType() *LevelUpdate {
	_u.mutation.ClearLevelType()
	return _u
}

// SetLevel sets the "level" field.
func (_u *LevelUpdate) SetLevel(v int64) *LevelUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableLevel(v *int64) *LevelUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *LevelUpdate) AddLevel(v int64) *LevelUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *LevelUpdate) ClearLevel() *LevelUpdate {
	_u.mutation.ClearLevel()
	return _u
}

// SetTotalExp sets the "total_exp" field.
func (_u *LevelUpdate) SetTotalExp(v int64) *LevelUpdate {
	_u.mutation.ResetTotalExp()
	_u.mutation.SetTotalExp(v)
	return _u
}

// SetNillableTotalExp sets the "total_exp" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableTotalExp(v *int64) *LevelUpdate {
	if v != nil {
		_u.SetTotalExp(*v)
	}
	return _u
}

// AddTotalExp adds value to the "total_exp" field.
func (_u *LevelUpdate) AddTotalExp(v int64) *LevelUpdate {
	_u.mutation.AddTotalExp(v)
	return _u
}

// ClearTotalExp clears the value of the "total_exp" field.
func (_u *LevelUpdate) ClearTotalExp() *LevelUpdate {
	_u.mutation.ClearTotalExp()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *LevelUpdate) SetServerRegion(v string) *LevelUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableServerRegion(v *string) *LevelUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the LevelMutation object of the builder.
func (_u *LevelUpdate) Mutation() *LevelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LevelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LevelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LevelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LevelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LevelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(level.Table, level.Columns, sqlgraph.NewFieldSpec(level.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(level.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(level.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(level.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LevelType(); ok {
		_spec.SetField(level.FieldLevelType, field.TypeString, value)
	}
	if _u.mutation.LevelTypeCleared() {
		_spec.ClearField(level.FieldLevelType, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(level.FieldLevel, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(level.FieldLevel, field.TypeInt64, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(level.FieldLevel, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalExp(); ok {
		_spec.SetField(level.FieldTotalExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalExp(); ok {
		_spec.AddField(level.FieldTotalExp, field.TypeInt64, value)
	}
	if _u.mutation.TotalExpCleared() {
		_spec.ClearField(level.FieldTotalExp, field.TypeInt64)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(level.FieldServerRegion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{level.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LevelUpdateOne is the builder for updating a single Level entity.
type LevelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LevelMutation
}

// SetGameID sets the "game_id" field.
func (_u *LevelUpdateOne) SetGameID(v int64) *LevelUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableGameID(v *int64) *LevelUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *LevelUpdateOne) AddGameID(v int64) *LevelUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *LevelUpdateOne) ClearGameID() *LevelUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetLevelType sets the "level_type" field.
func (_u *LevelUpdateOne) SetLevelType(v string) *LevelUpdateOne {
	_u.mutation.SetLevelType(v)
	return _u
}

// SetNillableLevelType sets the "level_type" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableLevelType(v *string) *LevelUpdateOne {
	if v != nil {
		_u.SetLevelType(*v)
	}
	return _u
}

// ClearLevelType clears the value of the "level_type" field.
func (_u *LevelUpdateOne) ClearLevelType() *LevelUpdateOne {
	_u.mutation.ClearLevelType()
	return _u
}

// SetLevel sets the "level" field.
func (_u *LevelUpdateOne) SetLevel(v int64) *LevelUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableLevel(v *int64) *LevelUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *LevelUpdateOne) AddLevel(v int64) *LevelUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *LevelUpdateOne) ClearLevel() *LevelUpdateOne {
	_u.mutation.ClearLevel()
	return _u
}

// SetTotalExp sets the "total_exp" field.
func (_u *LevelUpdateOne) SetTotalExp(v int64) *LevelUpdateOne {
	_u.mutation.ResetTotalExp()
	_u.mutation.SetTotalExp(v)
	return _u
}

// SetNillableTotalExp sets the "total_exp" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableTotalExp(v *int64) *LevelUpdateOne {
	if v != nil {
		_u.SetTotalExp(*v)
	}
	return _u
}

// AddTotalExp adds value to the "total_exp" field.
func (_u *LevelUpdateOne) AddTotalExp(v int64) *LevelUpdateOne {
	_u.mutation.AddTotalExp(v)
	return _u
}

// ClearTotalExp clears the value of the "total_exp" field.
func (_u *LevelUpdateOne) ClearTotalExp() *LevelUpdateOne {
	_u.mutation.ClearTotalExp()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *LevelUpdateOne) SetServerRegion(v string) *LevelUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableServerRegion(v *string) *LevelUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the LevelMutation object of the builder.
func (_u *LevelUpdateOne) Mutation() *LevelMutation {
	return _u.mutation
}

// Where appends a list predicates to the LevelUpdate builder.
func (_u *LevelUpdateOne) Where(ps ...predicate.Level) *LevelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LevelUpdateOne) Select(field string, fields ...string) *LevelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Level entity.
func (_u *LevelUpdateOne) Save(ctx context.Context) (*Level, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LevelUpdateOne) SaveX(ctx context.Context) *Level {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LevelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LevelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LevelUpdateOne) sqlSave(ctx context.Context) (_node *Level, err error) {
	_spec := sqlgraph.NewUpdateSpec(level.Table, level.Columns, sqlgraph.NewFieldSpec(level.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Level.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, level.FieldID)
		for _, f := range fields {
			if !level.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != level.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(level.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(level.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(level.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LevelType(); ok {
		_spec.SetField(level.FieldLevelType, field.TypeString, value)
	}
	if _u.mutation.LevelTypeCleared() {
		_spec.ClearField(level.FieldLevelType, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(level.FieldLevel, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(level.FieldLevel, field.TypeInt64, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(level.FieldLevel, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalExp(); ok {
		_spec.SetField(level.FieldTotalExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalExp(); ok {
		_spec.AddField(level.FieldTotalExp, field.TypeInt64, value)
	}
	if _u.mutation.TotalExpCleared() {
		_spec.ClearField(level.FieldTotalExp, field.TypeInt64)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(level.FieldServerRegion, field.TypeString, value)
	}
	_node = &Level{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{level.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
