// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"encoding/json"
	"fmt"
	"haruki-cloud/database/sekai/mysekaicharactertalkcondition"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Mysekaicharactertalkcondition is the model entity for the Mysekaicharactertalkcondition schema.
type Mysekaicharactertalkcondition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ServerRegion holds the value of the "server_region" field.
	ServerRegion string `json:"server_region,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID int64 `json:"game_id,omitempty"`
	// MysekaiCharacterTalkConditionType holds the value of the "mysekai_character_talk_condition_type" field.
	MysekaiCharacterTalkConditionType map[string]interface{} `json:"mysekai_character_talk_condition_type,omitempty"`
	// MysekaiCharacterTalkConditionTypeValue holds the value of the "mysekai_character_talk_condition_type_value" field.
	MysekaiCharacterTalkConditionTypeValue int64 `json:"mysekai_character_talk_condition_type_value,omitempty"`
	selectValues                           sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mysekaicharactertalkcondition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionType:
			values[i] = new([]byte)
		case mysekaicharactertalkcondition.FieldID, mysekaicharactertalkcondition.FieldGameID, mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionTypeValue:
			values[i] = new(sql.NullInt64)
		case mysekaicharactertalkcondition.FieldServerRegion:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mysekaicharactertalkcondition fields.
func (_m *Mysekaicharactertalkcondition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mysekaicharactertalkcondition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mysekaicharactertalkcondition.FieldServerRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_region", values[i])
			} else if value.Valid {
				_m.ServerRegion = value.String
			}
		case mysekaicharactertalkcondition.FieldGameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = value.Int64
			}
		case mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionType:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mysekai_character_talk_condition_type", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MysekaiCharacterTalkConditionType); err != nil {
					return fmt.Errorf("unmarshal field mysekai_character_talk_condition_type: %w", err)
				}
			}
		case mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionTypeValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mysekai_character_talk_condition_type_value", values[i])
			} else if value.Valid {
				_m.MysekaiCharacterTalkConditionTypeValue = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Mysekaicharactertalkcondition.
// This includes values selected through modifiers, order, etc.
func (_m *Mysekaicharactertalkcondition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Mysekaicharactertalkcondition.
// Note that you need to call Mysekaicharactertalkcondition.Unwrap() before calling this method if this Mysekaicharactertalkcondition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Mysekaicharactertalkcondition) Update() *MysekaicharactertalkconditionUpdateOne {
	return NewMysekaicharactertalkconditionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Mysekaicharactertalkcondition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Mysekaicharactertalkcondition) Unwrap() *Mysekaicharactertalkcondition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("sekai: Mysekaicharactertalkcondition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Mysekaicharactertalkcondition) String() string {
	var builder strings.Builder
	builder.WriteString("Mysekaicharactertalkcondition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("server_region=")
	builder.WriteString(_m.ServerRegion)
	builder.WriteString(", ")
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("mysekai_character_talk_condition_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MysekaiCharacterTalkConditionType))
	builder.WriteString(", ")
	builder.WriteString("mysekai_character_talk_condition_type_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.MysekaiCharacterTalkConditionTypeValue))
	builder.WriteByte(')')
	return builder.String()
}

// Mysekaicharactertalkconditions is a parsable slice of Mysekaicharactertalkcondition.
type Mysekaicharactertalkconditions []*Mysekaicharactertalkcondition
