// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"encoding/json"
	"fmt"
	"haruki-cloud/database/sekai/mysekaimusicrecord"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Mysekaimusicrecord is the model entity for the Mysekaimusicrecord schema.
type Mysekaimusicrecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID int `json:"game_id,omitempty"`
	// MysekaiMusicTrackType holds the value of the "mysekai_music_track_type" field.
	MysekaiMusicTrackType json.RawMessage `json:"mysekai_music_track_type,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID int `json:"external_id,omitempty"`
	// ServerRegion holds the value of the "server_region" field.
	ServerRegion string `json:"server_region,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mysekaimusicrecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mysekaimusicrecord.FieldMysekaiMusicTrackType:
			values[i] = new([]byte)
		case mysekaimusicrecord.FieldID, mysekaimusicrecord.FieldGameID, mysekaimusicrecord.FieldExternalID:
			values[i] = new(sql.NullInt64)
		case mysekaimusicrecord.FieldServerRegion:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mysekaimusicrecord fields.
func (_m *Mysekaimusicrecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mysekaimusicrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mysekaimusicrecord.FieldGameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = int(value.Int64)
			}
		case mysekaimusicrecord.FieldMysekaiMusicTrackType:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mysekai_music_track_type", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MysekaiMusicTrackType); err != nil {
					return fmt.Errorf("unmarshal field mysekai_music_track_type: %w", err)
				}
			}
		case mysekaimusicrecord.FieldExternalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = int(value.Int64)
			}
		case mysekaimusicrecord.FieldServerRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_region", values[i])
			} else if value.Valid {
				_m.ServerRegion = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Mysekaimusicrecord.
// This includes values selected through modifiers, order, etc.
func (_m *Mysekaimusicrecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Mysekaimusicrecord.
// Note that you need to call Mysekaimusicrecord.Unwrap() before calling this method if this Mysekaimusicrecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Mysekaimusicrecord) Update() *MysekaimusicrecordUpdateOne {
	return NewMysekaimusicrecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Mysekaimusicrecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Mysekaimusicrecord) Unwrap() *Mysekaimusicrecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("sekai: Mysekaimusicrecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Mysekaimusicrecord) String() string {
	var builder strings.Builder
	builder.WriteString("Mysekaimusicrecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("mysekai_music_track_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MysekaiMusicTrackType))
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalID))
	builder.WriteString(", ")
	builder.WriteString("server_region=")
	builder.WriteString(_m.ServerRegion)
	builder.WriteByte(')')
	return builder.String()
}

// Mysekaimusicrecords is a parsable slice of Mysekaimusicrecord.
type Mysekaimusicrecords []*Mysekaimusicrecord
