// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/mysekaicharactertalkcondition"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MysekaicharactertalkconditionCreate is the builder for creating a Mysekaicharactertalkcondition entity.
type MysekaicharactertalkconditionCreate struct {
	config
	mutation *MysekaicharactertalkconditionMutation
	hooks    []Hook
}

// SetServerRegion sets the "server_region" field.
func (_c *MysekaicharactertalkconditionCreate) SetServerRegion(v string) *MysekaicharactertalkconditionCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// SetGameID sets the "game_id" field.
func (_c *MysekaicharactertalkconditionCreate) SetGameID(v int64) *MysekaicharactertalkconditionCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_c *MysekaicharactertalkconditionCreate) SetNillableGameID(v *int64) *MysekaicharactertalkconditionCreate {
	if v != nil {
		_c.SetGameID(*v)
	}
	return _c
}

// SetMysekaiCharacterTalkConditionType sets the "mysekai_character_talk_condition_type" field.
func (_c *MysekaicharactertalkconditionCreate) SetMysekaiCharacterTalkConditionType(v map[string]interface{}) *MysekaicharactertalkconditionCreate {
	_c.mutation.SetMysekaiCharacterTalkConditionType(v)
	return _c
}

// SetMysekaiCharacterTalkConditionTypeValue sets the "mysekai_character_talk_condition_type_value" field.
func (_c *MysekaicharactertalkconditionCreate) SetMysekaiCharacterTalkConditionTypeValue(v int64) *MysekaicharactertalkconditionCreate {
	_c.mutation.SetMysekaiCharacterTalkConditionTypeValue(v)
	return _c
}

// SetNillableMysekaiCharacterTalkConditionTypeValue sets the "mysekai_character_talk_condition_type_value" field if the given value is not nil.
func (_c *MysekaicharactertalkconditionCreate) SetNillableMysekaiCharacterTalkConditionTypeValue(v *int64) *MysekaicharactertalkconditionCreate {
	if v != nil {
		_c.SetMysekaiCharacterTalkConditionTypeValue(*v)
	}
	return _c
}

// Mutation returns the MysekaicharactertalkconditionMutation object of the builder.
func (_c *MysekaicharactertalkconditionCreate) Mutation() *MysekaicharactertalkconditionMutation {
	return _c.mutation
}

// Save creates the Mysekaicharactertalkcondition in the database.
func (_c *MysekaicharactertalkconditionCreate) Save(ctx context.Context) (*Mysekaicharactertalkcondition, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MysekaicharactertalkconditionCreate) SaveX(ctx context.Context) *Mysekaicharactertalkcondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekaicharactertalkconditionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekaicharactertalkconditionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MysekaicharactertalkconditionCreate) check() error {
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Mysekaicharactertalkcondition.server_region"`)}
	}
	return nil
}

func (_c *MysekaicharactertalkconditionCreate) sqlSave(ctx context.Context) (*Mysekaicharactertalkcondition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MysekaicharactertalkconditionCreate) createSpec() (*Mysekaicharactertalkcondition, *sqlgraph.CreateSpec) {
	var (
		_node = &Mysekaicharactertalkcondition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mysekaicharactertalkcondition.Table, sqlgraph.NewFieldSpec(mysekaicharactertalkcondition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaicharactertalkcondition.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(mysekaicharactertalkcondition.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.MysekaiCharacterTalkConditionType(); ok {
		_spec.SetField(mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionType, field.TypeJSON, value)
		_node.MysekaiCharacterTalkConditionType = value
	}
	if value, ok := _c.mutation.MysekaiCharacterTalkConditionTypeValue(); ok {
		_spec.SetField(mysekaicharactertalkcondition.FieldMysekaiCharacterTalkConditionTypeValue, field.TypeInt64, value)
		_node.MysekaiCharacterTalkConditionTypeValue = value
	}
	return _node, _spec
}

// MysekaicharactertalkconditionCreateBulk is the builder for creating many Mysekaicharactertalkcondition entities in bulk.
type MysekaicharactertalkconditionCreateBulk struct {
	config
	err      error
	builders []*MysekaicharactertalkconditionCreate
}

// Save creates the Mysekaicharactertalkcondition entities in the database.
func (_c *MysekaicharactertalkconditionCreateBulk) Save(ctx context.Context) ([]*Mysekaicharactertalkcondition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mysekaicharactertalkcondition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MysekaicharactertalkconditionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MysekaicharactertalkconditionCreateBulk) SaveX(ctx context.Context) []*Mysekaicharactertalkcondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekaicharactertalkconditionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekaicharactertalkconditionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
