// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/mysekairankrelease"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MysekairankreleaseCreate is the builder for creating a Mysekairankrelease entity.
type MysekairankreleaseCreate struct {
	config
	mutation *MysekairankreleaseMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *MysekairankreleaseCreate) SetGameID(v int64) *MysekairankreleaseCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_c *MysekairankreleaseCreate) SetNillableGameID(v *int64) *MysekairankreleaseCreate {
	if v != nil {
		_c.SetGameID(*v)
	}
	return _c
}

// SetMysekaiRank sets the "mysekai_rank" field.
func (_c *MysekairankreleaseCreate) SetMysekaiRank(v int64) *MysekairankreleaseCreate {
	_c.mutation.SetMysekaiRank(v)
	return _c
}

// SetNillableMysekaiRank sets the "mysekai_rank" field if the given value is not nil.
func (_c *MysekairankreleaseCreate) SetNillableMysekaiRank(v *int64) *MysekairankreleaseCreate {
	if v != nil {
		_c.SetMysekaiRank(*v)
	}
	return _c
}

// SetMysekaiRankRelaseType sets the "mysekai_rank_relase_type" field.
func (_c *MysekairankreleaseCreate) SetMysekaiRankRelaseType(v string) *MysekairankreleaseCreate {
	_c.mutation.SetMysekaiRankRelaseType(v)
	return _c
}

// SetNillableMysekaiRankRelaseType sets the "mysekai_rank_relase_type" field if the given value is not nil.
func (_c *MysekairankreleaseCreate) SetNillableMysekaiRankRelaseType(v *string) *MysekairankreleaseCreate {
	if v != nil {
		_c.SetMysekaiRankRelaseType(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *MysekairankreleaseCreate) SetExternalID(v int64) *MysekairankreleaseCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *MysekairankreleaseCreate) SetNillableExternalID(v *int64) *MysekairankreleaseCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *MysekairankreleaseCreate) SetServerRegion(v string) *MysekairankreleaseCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the MysekairankreleaseMutation object of the builder.
func (_c *MysekairankreleaseCreate) Mutation() *MysekairankreleaseMutation {
	return _c.mutation
}

// Save creates the Mysekairankrelease in the database.
func (_c *MysekairankreleaseCreate) Save(ctx context.Context) (*Mysekairankrelease, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MysekairankreleaseCreate) SaveX(ctx context.Context) *Mysekairankrelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekairankreleaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekairankreleaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MysekairankreleaseCreate) check() error {
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Mysekairankrelease.server_region"`)}
	}
	return nil
}

func (_c *MysekairankreleaseCreate) sqlSave(ctx context.Context) (*Mysekairankrelease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MysekairankreleaseCreate) createSpec() (*Mysekairankrelease, *sqlgraph.CreateSpec) {
	var (
		_node = &Mysekairankrelease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mysekairankrelease.Table, sqlgraph.NewFieldSpec(mysekairankrelease.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(mysekairankrelease.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.MysekaiRank(); ok {
		_spec.SetField(mysekairankrelease.FieldMysekaiRank, field.TypeInt64, value)
		_node.MysekaiRank = value
	}
	if value, ok := _c.mutation.MysekaiRankRelaseType(); ok {
		_spec.SetField(mysekairankrelease.FieldMysekaiRankRelaseType, field.TypeString, value)
		_node.MysekaiRankRelaseType = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(mysekairankrelease.FieldExternalID, field.TypeInt64, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(mysekairankrelease.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// MysekairankreleaseCreateBulk is the builder for creating many Mysekairankrelease entities in bulk.
type MysekairankreleaseCreateBulk struct {
	config
	err      error
	builders []*MysekairankreleaseCreate
}

// Save creates the Mysekairankrelease entities in the database.
func (_c *MysekairankreleaseCreateBulk) Save(ctx context.Context) ([]*Mysekairankrelease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mysekairankrelease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MysekairankreleaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MysekairankreleaseCreateBulk) SaveX(ctx context.Context) []*Mysekairankrelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekairankreleaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekairankreleaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
