// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/mysekaigatecommonskin"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MysekaigatecommonskinUpdate is the builder for updating Mysekaigatecommonskin entities.
type MysekaigatecommonskinUpdate struct {
	config
	hooks    []Hook
	mutation *MysekaigatecommonskinMutation
}

// Where appends a list predicates to the MysekaigatecommonskinUpdate builder.
func (_u *MysekaigatecommonskinUpdate) Where(ps ...predicate.Mysekaigatecommonskin) *MysekaigatecommonskinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *MysekaigatecommonskinUpdate) SetGameID(v int64) *MysekaigatecommonskinUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdate) SetNillableGameID(v *int64) *MysekaigatecommonskinUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *MysekaigatecommonskinUpdate) AddGameID(v int64) *MysekaigatecommonskinUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *MysekaigatecommonskinUpdate) ClearGameID() *MysekaigatecommonskinUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetName sets the "name" field.
func (_u *MysekaigatecommonskinUpdate) SetName(v string) *MysekaigatecommonskinUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdate) SetNillableName(v *string) *MysekaigatecommonskinUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *MysekaigatecommonskinUpdate) ClearName() *MysekaigatecommonskinUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_u *MysekaigatecommonskinUpdate) SetAssetbundleName(v string) *MysekaigatecommonskinUpdate {
	_u.mutation.SetAssetbundleName(v)
	return _u
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdate) SetNillableAssetbundleName(v *string) *MysekaigatecommonskinUpdate {
	if v != nil {
		_u.SetAssetbundleName(*v)
	}
	return _u
}

// ClearAssetbundleName clears the value of the "assetbundle_name" field.
func (_u *MysekaigatecommonskinUpdate) ClearAssetbundleName() *MysekaigatecommonskinUpdate {
	_u.mutation.ClearAssetbundleName()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *MysekaigatecommonskinUpdate) SetServerRegion(v string) *MysekaigatecommonskinUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdate) SetNillableServerRegion(v *string) *MysekaigatecommonskinUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the MysekaigatecommonskinMutation object of the builder.
func (_u *MysekaigatecommonskinUpdate) Mutation() *MysekaigatecommonskinMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MysekaigatecommonskinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MysekaigatecommonskinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MysekaigatecommonskinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MysekaigatecommonskinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MysekaigatecommonskinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mysekaigatecommonskin.Table, mysekaigatecommonskin.Columns, sqlgraph.NewFieldSpec(mysekaigatecommonskin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(mysekaigatecommonskin.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AssetbundleName(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldAssetbundleName, field.TypeString, value)
	}
	if _u.mutation.AssetbundleNameCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldAssetbundleName, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldServerRegion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mysekaigatecommonskin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MysekaigatecommonskinUpdateOne is the builder for updating a single Mysekaigatecommonskin entity.
type MysekaigatecommonskinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MysekaigatecommonskinMutation
}

// SetGameID sets the "game_id" field.
func (_u *MysekaigatecommonskinUpdateOne) SetGameID(v int64) *MysekaigatecommonskinUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdateOne) SetNillableGameID(v *int64) *MysekaigatecommonskinUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *MysekaigatecommonskinUpdateOne) AddGameID(v int64) *MysekaigatecommonskinUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *MysekaigatecommonskinUpdateOne) ClearGameID() *MysekaigatecommonskinUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetName sets the "name" field.
func (_u *MysekaigatecommonskinUpdateOne) SetName(v string) *MysekaigatecommonskinUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdateOne) SetNillableName(v *string) *MysekaigatecommonskinUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *MysekaigatecommonskinUpdateOne) ClearName() *MysekaigatecommonskinUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_u *MysekaigatecommonskinUpdateOne) SetAssetbundleName(v string) *MysekaigatecommonskinUpdateOne {
	_u.mutation.SetAssetbundleName(v)
	return _u
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdateOne) SetNillableAssetbundleName(v *string) *MysekaigatecommonskinUpdateOne {
	if v != nil {
		_u.SetAssetbundleName(*v)
	}
	return _u
}

// ClearAssetbundleName clears the value of the "assetbundle_name" field.
func (_u *MysekaigatecommonskinUpdateOne) ClearAssetbundleName() *MysekaigatecommonskinUpdateOne {
	_u.mutation.ClearAssetbundleName()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *MysekaigatecommonskinUpdateOne) SetServerRegion(v string) *MysekaigatecommonskinUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *MysekaigatecommonskinUpdateOne) SetNillableServerRegion(v *string) *MysekaigatecommonskinUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the MysekaigatecommonskinMutation object of the builder.
func (_u *MysekaigatecommonskinUpdateOne) Mutation() *MysekaigatecommonskinMutation {
	return _u.mutation
}

// Where appends a list predicates to the MysekaigatecommonskinUpdate builder.
func (_u *MysekaigatecommonskinUpdateOne) Where(ps ...predicate.Mysekaigatecommonskin) *MysekaigatecommonskinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MysekaigatecommonskinUpdateOne) Select(field string, fields ...string) *MysekaigatecommonskinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Mysekaigatecommonskin entity.
func (_u *MysekaigatecommonskinUpdateOne) Save(ctx context.Context) (*Mysekaigatecommonskin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MysekaigatecommonskinUpdateOne) SaveX(ctx context.Context) *Mysekaigatecommonskin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MysekaigatecommonskinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MysekaigatecommonskinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MysekaigatecommonskinUpdateOne) sqlSave(ctx context.Context) (_node *Mysekaigatecommonskin, err error) {
	_spec := sqlgraph.NewUpdateSpec(mysekaigatecommonskin.Table, mysekaigatecommonskin.Columns, sqlgraph.NewFieldSpec(mysekaigatecommonskin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Mysekaigatecommonskin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mysekaigatecommonskin.FieldID)
		for _, f := range fields {
			if !mysekaigatecommonskin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != mysekaigatecommonskin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(mysekaigatecommonskin.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AssetbundleName(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldAssetbundleName, field.TypeString, value)
	}
	if _u.mutation.AssetbundleNameCleared() {
		_spec.ClearField(mysekaigatecommonskin.FieldAssetbundleName, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaigatecommonskin.FieldServerRegion, field.TypeString, value)
	}
	_node = &Mysekaigatecommonskin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mysekaigatecommonskin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
