// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/mysekaicharactertalkconditiongroup"
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MysekaicharactertalkconditiongroupUpdate is the builder for updating Mysekaicharactertalkconditiongroup entities.
type MysekaicharactertalkconditiongroupUpdate struct {
	config
	hooks    []Hook
	mutation *MysekaicharactertalkconditiongroupMutation
}

// Where appends a list predicates to the MysekaicharactertalkconditiongroupUpdate builder.
func (_u *MysekaicharactertalkconditiongroupUpdate) Where(ps ...predicate.Mysekaicharactertalkconditiongroup) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetServerRegion(v string) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetNillableServerRegion(v *string) *MysekaicharactertalkconditiongroupUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetGameID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetNillableGameID(v *int64) *MysekaicharactertalkconditiongroupUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) AddGameID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) ClearGameID() *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetGroupID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetNillableGroupID(v *int64) *MysekaicharactertalkconditiongroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) AddGroupID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) ClearGroupID() *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetMysekaiCharacterTalkConditionID sets the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetMysekaiCharacterTalkConditionID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ResetMysekaiCharacterTalkConditionID()
	_u.mutation.SetMysekaiCharacterTalkConditionID(v)
	return _u
}

// SetNillableMysekaiCharacterTalkConditionID sets the "mysekai_character_talk_condition_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdate) SetNillableMysekaiCharacterTalkConditionID(v *int64) *MysekaicharactertalkconditiongroupUpdate {
	if v != nil {
		_u.SetMysekaiCharacterTalkConditionID(*v)
	}
	return _u
}

// AddMysekaiCharacterTalkConditionID adds value to the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) AddMysekaiCharacterTalkConditionID(v int64) *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.AddMysekaiCharacterTalkConditionID(v)
	return _u
}

// ClearMysekaiCharacterTalkConditionID clears the value of the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdate) ClearMysekaiCharacterTalkConditionID() *MysekaicharactertalkconditiongroupUpdate {
	_u.mutation.ClearMysekaiCharacterTalkConditionID()
	return _u
}

// Mutation returns the MysekaicharactertalkconditiongroupMutation object of the builder.
func (_u *MysekaicharactertalkconditiongroupUpdate) Mutation() *MysekaicharactertalkconditiongroupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MysekaicharactertalkconditiongroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MysekaicharactertalkconditiongroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MysekaicharactertalkconditiongroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MysekaicharactertalkconditiongroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MysekaicharactertalkconditiongroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mysekaicharactertalkconditiongroup.Table, mysekaicharactertalkconditiongroup.Columns, sqlgraph.NewFieldSpec(mysekaicharactertalkconditiongroup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldServerRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MysekaiCharacterTalkConditionID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMysekaiCharacterTalkConditionID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64, value)
	}
	if _u.mutation.MysekaiCharacterTalkConditionIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mysekaicharactertalkconditiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MysekaicharactertalkconditiongroupUpdateOne is the builder for updating a single Mysekaicharactertalkconditiongroup entity.
type MysekaicharactertalkconditiongroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MysekaicharactertalkconditiongroupMutation
}

// SetServerRegion sets the "server_region" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetServerRegion(v string) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetNillableServerRegion(v *string) *MysekaicharactertalkconditiongroupUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetGameID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetNillableGameID(v *int64) *MysekaicharactertalkconditiongroupUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) AddGameID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) ClearGameID() *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetGroupID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetNillableGroupID(v *int64) *MysekaicharactertalkconditiongroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) AddGroupID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) ClearGroupID() *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetMysekaiCharacterTalkConditionID sets the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetMysekaiCharacterTalkConditionID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ResetMysekaiCharacterTalkConditionID()
	_u.mutation.SetMysekaiCharacterTalkConditionID(v)
	return _u
}

// SetNillableMysekaiCharacterTalkConditionID sets the "mysekai_character_talk_condition_id" field if the given value is not nil.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SetNillableMysekaiCharacterTalkConditionID(v *int64) *MysekaicharactertalkconditiongroupUpdateOne {
	if v != nil {
		_u.SetMysekaiCharacterTalkConditionID(*v)
	}
	return _u
}

// AddMysekaiCharacterTalkConditionID adds value to the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) AddMysekaiCharacterTalkConditionID(v int64) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.AddMysekaiCharacterTalkConditionID(v)
	return _u
}

// ClearMysekaiCharacterTalkConditionID clears the value of the "mysekai_character_talk_condition_id" field.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) ClearMysekaiCharacterTalkConditionID() *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.ClearMysekaiCharacterTalkConditionID()
	return _u
}

// Mutation returns the MysekaicharactertalkconditiongroupMutation object of the builder.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) Mutation() *MysekaicharactertalkconditiongroupMutation {
	return _u.mutation
}

// Where appends a list predicates to the MysekaicharactertalkconditiongroupUpdate builder.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) Where(ps ...predicate.Mysekaicharactertalkconditiongroup) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) Select(field string, fields ...string) *MysekaicharactertalkconditiongroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Mysekaicharactertalkconditiongroup entity.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) Save(ctx context.Context) (*Mysekaicharactertalkconditiongroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) SaveX(ctx context.Context) *Mysekaicharactertalkconditiongroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MysekaicharactertalkconditiongroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MysekaicharactertalkconditiongroupUpdateOne) sqlSave(ctx context.Context) (_node *Mysekaicharactertalkconditiongroup, err error) {
	_spec := sqlgraph.NewUpdateSpec(mysekaicharactertalkconditiongroup.Table, mysekaicharactertalkconditiongroup.Columns, sqlgraph.NewFieldSpec(mysekaicharactertalkconditiongroup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Mysekaicharactertalkconditiongroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mysekaicharactertalkconditiongroup.FieldID)
		for _, f := range fields {
			if !mysekaicharactertalkconditiongroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != mysekaicharactertalkconditiongroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldServerRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.MysekaiCharacterTalkConditionID(); ok {
		_spec.SetField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMysekaiCharacterTalkConditionID(); ok {
		_spec.AddField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64, value)
	}
	if _u.mutation.MysekaiCharacterTalkConditionIDCleared() {
		_spec.ClearField(mysekaicharactertalkconditiongroup.FieldMysekaiCharacterTalkConditionID, field.TypeInt64)
	}
	_node = &Mysekaicharactertalkconditiongroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mysekaicharactertalkconditiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
