// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/mysekaisiteharvestfixture"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MysekaisiteharvestfixtureCreate is the builder for creating a Mysekaisiteharvestfixture entity.
type MysekaisiteharvestfixtureCreate struct {
	config
	mutation *MysekaisiteharvestfixtureMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *MysekaisiteharvestfixtureCreate) SetGameID(v int64) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetMysekaiSiteHarvestFixtureType sets the "mysekai_site_harvest_fixture_type" field.
func (_c *MysekaisiteharvestfixtureCreate) SetMysekaiSiteHarvestFixtureType(v string) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetMysekaiSiteHarvestFixtureType(v)
	return _c
}

// SetNillableMysekaiSiteHarvestFixtureType sets the "mysekai_site_harvest_fixture_type" field if the given value is not nil.
func (_c *MysekaisiteharvestfixtureCreate) SetNillableMysekaiSiteHarvestFixtureType(v *string) *MysekaisiteharvestfixtureCreate {
	if v != nil {
		_c.SetMysekaiSiteHarvestFixtureType(*v)
	}
	return _c
}

// SetHp sets the "hp" field.
func (_c *MysekaisiteharvestfixtureCreate) SetHp(v int64) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetHp(v)
	return _c
}

// SetNillableHp sets the "hp" field if the given value is not nil.
func (_c *MysekaisiteharvestfixtureCreate) SetNillableHp(v *int64) *MysekaisiteharvestfixtureCreate {
	if v != nil {
		_c.SetHp(*v)
	}
	return _c
}

// SetLastAttackStamina sets the "last_attack_stamina" field.
func (_c *MysekaisiteharvestfixtureCreate) SetLastAttackStamina(v int64) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetLastAttackStamina(v)
	return _c
}

// SetNillableLastAttackStamina sets the "last_attack_stamina" field if the given value is not nil.
func (_c *MysekaisiteharvestfixtureCreate) SetNillableLastAttackStamina(v *int64) *MysekaisiteharvestfixtureCreate {
	if v != nil {
		_c.SetLastAttackStamina(*v)
	}
	return _c
}

// SetMysekaiSiteHarvestFixtureRarityType sets the "mysekai_site_harvest_fixture_rarity_type" field.
func (_c *MysekaisiteharvestfixtureCreate) SetMysekaiSiteHarvestFixtureRarityType(v json.RawMessage) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetMysekaiSiteHarvestFixtureRarityType(v)
	return _c
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_c *MysekaisiteharvestfixtureCreate) SetAssetbundleName(v string) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetAssetbundleName(v)
	return _c
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_c *MysekaisiteharvestfixtureCreate) SetNillableAssetbundleName(v *string) *MysekaisiteharvestfixtureCreate {
	if v != nil {
		_c.SetAssetbundleName(*v)
	}
	return _c
}

// SetServerRegion sets the "server_region" field.
func (_c *MysekaisiteharvestfixtureCreate) SetServerRegion(v string) *MysekaisiteharvestfixtureCreate {
	_c.mutation.SetServerRegion(v)
	return _c
}

// Mutation returns the MysekaisiteharvestfixtureMutation object of the builder.
func (_c *MysekaisiteharvestfixtureCreate) Mutation() *MysekaisiteharvestfixtureMutation {
	return _c.mutation
}

// Save creates the Mysekaisiteharvestfixture in the database.
func (_c *MysekaisiteharvestfixtureCreate) Save(ctx context.Context) (*Mysekaisiteharvestfixture, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MysekaisiteharvestfixtureCreate) SaveX(ctx context.Context) *Mysekaisiteharvestfixture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekaisiteharvestfixtureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekaisiteharvestfixtureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MysekaisiteharvestfixtureCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`sekai: missing required field "Mysekaisiteharvestfixture.game_id"`)}
	}
	if _, ok := _c.mutation.ServerRegion(); !ok {
		return &ValidationError{Name: "server_region", err: errors.New(`sekai: missing required field "Mysekaisiteharvestfixture.server_region"`)}
	}
	return nil
}

func (_c *MysekaisiteharvestfixtureCreate) sqlSave(ctx context.Context) (*Mysekaisiteharvestfixture, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MysekaisiteharvestfixtureCreate) createSpec() (*Mysekaisiteharvestfixture, *sqlgraph.CreateSpec) {
	var (
		_node = &Mysekaisiteharvestfixture{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mysekaisiteharvestfixture.Table, sqlgraph.NewFieldSpec(mysekaisiteharvestfixture.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GameID(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldGameID, field.TypeInt64, value)
		_node.GameID = value
	}
	if value, ok := _c.mutation.MysekaiSiteHarvestFixtureType(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldMysekaiSiteHarvestFixtureType, field.TypeString, value)
		_node.MysekaiSiteHarvestFixtureType = value
	}
	if value, ok := _c.mutation.Hp(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldHp, field.TypeInt64, value)
		_node.Hp = value
	}
	if value, ok := _c.mutation.LastAttackStamina(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldLastAttackStamina, field.TypeInt64, value)
		_node.LastAttackStamina = value
	}
	if value, ok := _c.mutation.MysekaiSiteHarvestFixtureRarityType(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldMysekaiSiteHarvestFixtureRarityType, field.TypeJSON, value)
		_node.MysekaiSiteHarvestFixtureRarityType = value
	}
	if value, ok := _c.mutation.AssetbundleName(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldAssetbundleName, field.TypeString, value)
		_node.AssetbundleName = value
	}
	if value, ok := _c.mutation.ServerRegion(); ok {
		_spec.SetField(mysekaisiteharvestfixture.FieldServerRegion, field.TypeString, value)
		_node.ServerRegion = value
	}
	return _node, _spec
}

// MysekaisiteharvestfixtureCreateBulk is the builder for creating many Mysekaisiteharvestfixture entities in bulk.
type MysekaisiteharvestfixtureCreateBulk struct {
	config
	err      error
	builders []*MysekaisiteharvestfixtureCreate
}

// Save creates the Mysekaisiteharvestfixture entities in the database.
func (_c *MysekaisiteharvestfixtureCreateBulk) Save(ctx context.Context) ([]*Mysekaisiteharvestfixture, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mysekaisiteharvestfixture, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MysekaisiteharvestfixtureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MysekaisiteharvestfixtureCreateBulk) SaveX(ctx context.Context) []*Mysekaisiteharvestfixture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MysekaisiteharvestfixtureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MysekaisiteharvestfixtureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
