// Code generated by ent, DO NOT EDIT.

package sekai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"haruki-cloud/database/sekai/predicate"
	"haruki-cloud/database/sekai/resourceboxe"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ResourceboxeUpdate is the builder for updating Resourceboxe entities.
type ResourceboxeUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceboxeMutation
}

// Where appends a list predicates to the ResourceboxeUpdate builder.
func (_u *ResourceboxeUpdate) Where(ps ...predicate.Resourceboxe) *ResourceboxeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetResourceBoxPurpose sets the "resource_box_purpose" field.
func (_u *ResourceboxeUpdate) SetResourceBoxPurpose(v string) *ResourceboxeUpdate {
	_u.mutation.SetResourceBoxPurpose(v)
	return _u
}

// SetNillableResourceBoxPurpose sets the "resource_box_purpose" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableResourceBoxPurpose(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetResourceBoxPurpose(*v)
	}
	return _u
}

// ClearResourceBoxPurpose clears the value of the "resource_box_purpose" field.
func (_u *ResourceboxeUpdate) ClearResourceBoxPurpose() *ResourceboxeUpdate {
	_u.mutation.ClearResourceBoxPurpose()
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *ResourceboxeUpdate) SetGameID(v int64) *ResourceboxeUpdate {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableGameID(v *int64) *ResourceboxeUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *ResourceboxeUpdate) AddGameID(v int64) *ResourceboxeUpdate {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *ResourceboxeUpdate) ClearGameID() *ResourceboxeUpdate {
	_u.mutation.ClearGameID()
	return _u
}

// SetResourceBoxType sets the "resource_box_type" field.
func (_u *ResourceboxeUpdate) SetResourceBoxType(v string) *ResourceboxeUpdate {
	_u.mutation.SetResourceBoxType(v)
	return _u
}

// SetNillableResourceBoxType sets the "resource_box_type" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableResourceBoxType(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetResourceBoxType(*v)
	}
	return _u
}

// ClearResourceBoxType clears the value of the "resource_box_type" field.
func (_u *ResourceboxeUpdate) ClearResourceBoxType() *ResourceboxeUpdate {
	_u.mutation.ClearResourceBoxType()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourceboxeUpdate) SetDescription(v string) *ResourceboxeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableDescription(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ResourceboxeUpdate) ClearDescription() *ResourceboxeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDetails sets the "details" field.
func (_u *ResourceboxeUpdate) SetDetails(v json.RawMessage) *ResourceboxeUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// AppendDetails appends value to the "details" field.
func (_u *ResourceboxeUpdate) AppendDetails(v json.RawMessage) *ResourceboxeUpdate {
	_u.mutation.AppendDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ResourceboxeUpdate) ClearDetails() *ResourceboxeUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceboxeUpdate) SetName(v string) *ResourceboxeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableName(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ResourceboxeUpdate) ClearName() *ResourceboxeUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_u *ResourceboxeUpdate) SetAssetbundleName(v string) *ResourceboxeUpdate {
	_u.mutation.SetAssetbundleName(v)
	return _u
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableAssetbundleName(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetAssetbundleName(*v)
	}
	return _u
}

// ClearAssetbundleName clears the value of the "assetbundle_name" field.
func (_u *ResourceboxeUpdate) ClearAssetbundleName() *ResourceboxeUpdate {
	_u.mutation.ClearAssetbundleName()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *ResourceboxeUpdate) SetServerRegion(v string) *ResourceboxeUpdate {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *ResourceboxeUpdate) SetNillableServerRegion(v *string) *ResourceboxeUpdate {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the ResourceboxeMutation object of the builder.
func (_u *ResourceboxeUpdate) Mutation() *ResourceboxeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceboxeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceboxeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceboxeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceboxeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ResourceboxeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(resourceboxe.Table, resourceboxe.Columns, sqlgraph.NewFieldSpec(resourceboxe.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceBoxPurpose(); ok {
		_spec.SetField(resourceboxe.FieldResourceBoxPurpose, field.TypeString, value)
	}
	if _u.mutation.ResourceBoxPurposeCleared() {
		_spec.ClearField(resourceboxe.FieldResourceBoxPurpose, field.TypeString)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(resourceboxe.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(resourceboxe.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(resourceboxe.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResourceBoxType(); ok {
		_spec.SetField(resourceboxe.FieldResourceBoxType, field.TypeString, value)
	}
	if _u.mutation.ResourceBoxTypeCleared() {
		_spec.ClearField(resourceboxe.FieldResourceBoxType, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resourceboxe.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(resourceboxe.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(resourceboxe.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resourceboxe.FieldDetails, value)
		})
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(resourceboxe.FieldDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resourceboxe.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(resourceboxe.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AssetbundleName(); ok {
		_spec.SetField(resourceboxe.FieldAssetbundleName, field.TypeString, value)
	}
	if _u.mutation.AssetbundleNameCleared() {
		_spec.ClearField(resourceboxe.FieldAssetbundleName, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(resourceboxe.FieldServerRegion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceboxe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceboxeUpdateOne is the builder for updating a single Resourceboxe entity.
type ResourceboxeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceboxeMutation
}

// SetResourceBoxPurpose sets the "resource_box_purpose" field.
func (_u *ResourceboxeUpdateOne) SetResourceBoxPurpose(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetResourceBoxPurpose(v)
	return _u
}

// SetNillableResourceBoxPurpose sets the "resource_box_purpose" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableResourceBoxPurpose(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetResourceBoxPurpose(*v)
	}
	return _u
}

// ClearResourceBoxPurpose clears the value of the "resource_box_purpose" field.
func (_u *ResourceboxeUpdateOne) ClearResourceBoxPurpose() *ResourceboxeUpdateOne {
	_u.mutation.ClearResourceBoxPurpose()
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *ResourceboxeUpdateOne) SetGameID(v int64) *ResourceboxeUpdateOne {
	_u.mutation.ResetGameID()
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableGameID(v *int64) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// AddGameID adds value to the "game_id" field.
func (_u *ResourceboxeUpdateOne) AddGameID(v int64) *ResourceboxeUpdateOne {
	_u.mutation.AddGameID(v)
	return _u
}

// ClearGameID clears the value of the "game_id" field.
func (_u *ResourceboxeUpdateOne) ClearGameID() *ResourceboxeUpdateOne {
	_u.mutation.ClearGameID()
	return _u
}

// SetResourceBoxType sets the "resource_box_type" field.
func (_u *ResourceboxeUpdateOne) SetResourceBoxType(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetResourceBoxType(v)
	return _u
}

// SetNillableResourceBoxType sets the "resource_box_type" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableResourceBoxType(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetResourceBoxType(*v)
	}
	return _u
}

// ClearResourceBoxType clears the value of the "resource_box_type" field.
func (_u *ResourceboxeUpdateOne) ClearResourceBoxType() *ResourceboxeUpdateOne {
	_u.mutation.ClearResourceBoxType()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourceboxeUpdateOne) SetDescription(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableDescription(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ResourceboxeUpdateOne) ClearDescription() *ResourceboxeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDetails sets the "details" field.
func (_u *ResourceboxeUpdateOne) SetDetails(v json.RawMessage) *ResourceboxeUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// AppendDetails appends value to the "details" field.
func (_u *ResourceboxeUpdateOne) AppendDetails(v json.RawMessage) *ResourceboxeUpdateOne {
	_u.mutation.AppendDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ResourceboxeUpdateOne) ClearDetails() *ResourceboxeUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceboxeUpdateOne) SetName(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableName(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ResourceboxeUpdateOne) ClearName() *ResourceboxeUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAssetbundleName sets the "assetbundle_name" field.
func (_u *ResourceboxeUpdateOne) SetAssetbundleName(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetAssetbundleName(v)
	return _u
}

// SetNillableAssetbundleName sets the "assetbundle_name" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableAssetbundleName(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetAssetbundleName(*v)
	}
	return _u
}

// ClearAssetbundleName clears the value of the "assetbundle_name" field.
func (_u *ResourceboxeUpdateOne) ClearAssetbundleName() *ResourceboxeUpdateOne {
	_u.mutation.ClearAssetbundleName()
	return _u
}

// SetServerRegion sets the "server_region" field.
func (_u *ResourceboxeUpdateOne) SetServerRegion(v string) *ResourceboxeUpdateOne {
	_u.mutation.SetServerRegion(v)
	return _u
}

// SetNillableServerRegion sets the "server_region" field if the given value is not nil.
func (_u *ResourceboxeUpdateOne) SetNillableServerRegion(v *string) *ResourceboxeUpdateOne {
	if v != nil {
		_u.SetServerRegion(*v)
	}
	return _u
}

// Mutation returns the ResourceboxeMutation object of the builder.
func (_u *ResourceboxeUpdateOne) Mutation() *ResourceboxeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceboxeUpdate builder.
func (_u *ResourceboxeUpdateOne) Where(ps ...predicate.Resourceboxe) *ResourceboxeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceboxeUpdateOne) Select(field string, fields ...string) *ResourceboxeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resourceboxe entity.
func (_u *ResourceboxeUpdateOne) Save(ctx context.Context) (*Resourceboxe, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceboxeUpdateOne) SaveX(ctx context.Context) *Resourceboxe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceboxeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceboxeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ResourceboxeUpdateOne) sqlSave(ctx context.Context) (_node *Resourceboxe, err error) {
	_spec := sqlgraph.NewUpdateSpec(resourceboxe.Table, resourceboxe.Columns, sqlgraph.NewFieldSpec(resourceboxe.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`sekai: missing "Resourceboxe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceboxe.FieldID)
		for _, f := range fields {
			if !resourceboxe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("sekai: invalid field %q for query", f)}
			}
			if f != resourceboxe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceBoxPurpose(); ok {
		_spec.SetField(resourceboxe.FieldResourceBoxPurpose, field.TypeString, value)
	}
	if _u.mutation.ResourceBoxPurposeCleared() {
		_spec.ClearField(resourceboxe.FieldResourceBoxPurpose, field.TypeString)
	}
	if value, ok := _u.mutation.GameID(); ok {
		_spec.SetField(resourceboxe.FieldGameID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGameID(); ok {
		_spec.AddField(resourceboxe.FieldGameID, field.TypeInt64, value)
	}
	if _u.mutation.GameIDCleared() {
		_spec.ClearField(resourceboxe.FieldGameID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResourceBoxType(); ok {
		_spec.SetField(resourceboxe.FieldResourceBoxType, field.TypeString, value)
	}
	if _u.mutation.ResourceBoxTypeCleared() {
		_spec.ClearField(resourceboxe.FieldResourceBoxType, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resourceboxe.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(resourceboxe.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(resourceboxe.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resourceboxe.FieldDetails, value)
		})
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(resourceboxe.FieldDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resourceboxe.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(resourceboxe.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AssetbundleName(); ok {
		_spec.SetField(resourceboxe.FieldAssetbundleName, field.TypeString, value)
	}
	if _u.mutation.AssetbundleNameCleared() {
		_spec.ClearField(resourceboxe.FieldAssetbundleName, field.TypeString)
	}
	if value, ok := _u.mutation.ServerRegion(); ok {
		_spec.SetField(resourceboxe.FieldServerRegion, field.TypeString, value)
	}
	_node = &Resourceboxe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceboxe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
