// Code generated by ent, DO NOT EDIT.

package userpreference

import (
	"haruki-cloud/ent/pjsk/schema"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userpreference type in the database.
	Label = "user_preference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHarukiUserID holds the string denoting the haruki_user_id field in the database.
	FieldHarukiUserID = "haruki_user_id"
	// FieldSettings holds the string denoting the settings field in the database.
	FieldSettings = "settings"
	// Table holds the table name of the userpreference in the database.
	Table = "user_preferences"
)

// Columns holds all SQL columns for userpreference fields.
var Columns = []string{
	FieldID,
	FieldHarukiUserID,
	FieldSettings,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSettings holds the default value on creation for the "settings" field.
	DefaultSettings func() *schema.UserSettings
)

// OrderOption defines the ordering options for the UserPreference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHarukiUserID orders the results by the haruki_user_id field.
func ByHarukiUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHarukiUserID, opts...).ToFunc()
}
