// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"context"
	"errors"
	"fmt"
	"haruki-cloud/database/pjsk/aliassubmissionban"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AliasSubmissionBanCreate is the builder for creating a AliasSubmissionBan entity.
type AliasSubmissionBanCreate struct {
	config
	mutation *AliasSubmissionBanMutation
	hooks    []Hook
}

// SetPlatform sets the "platform" field.
func (_c *AliasSubmissionBanCreate) SetPlatform(v string) *AliasSubmissionBanCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_c *AliasSubmissionBanCreate) SetPlatformUserID(v string) *AliasSubmissionBanCreate {
	_c.mutation.SetPlatformUserID(v)
	return _c
}

// SetBannedBy sets the "banned_by" field.
func (_c *AliasSubmissionBanCreate) SetBannedBy(v string) *AliasSubmissionBanCreate {
	_c.mutation.SetBannedBy(v)
	return _c
}

// SetBannedAt sets the "banned_at" field.
func (_c *AliasSubmissionBanCreate) SetBannedAt(v time.Time) *AliasSubmissionBanCreate {
	_c.mutation.SetBannedAt(v)
	return _c
}

// Mutation returns the AliasSubmissionBanMutation object of the builder.
func (_c *AliasSubmissionBanCreate) Mutation() *AliasSubmissionBanMutation {
	return _c.mutation
}

// Save creates the AliasSubmissionBan in the database.
func (_c *AliasSubmissionBanCreate) Save(ctx context.Context) (*AliasSubmissionBan, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AliasSubmissionBanCreate) SaveX(ctx context.Context) *AliasSubmissionBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AliasSubmissionBanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AliasSubmissionBanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AliasSubmissionBanCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`pjsk: missing required field "AliasSubmissionBan.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := aliassubmissionban.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`pjsk: validator failed for field "AliasSubmissionBan.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformUserID(); !ok {
		return &ValidationError{Name: "platform_user_id", err: errors.New(`pjsk: missing required field "AliasSubmissionBan.platform_user_id"`)}
	}
	if v, ok := _c.mutation.PlatformUserID(); ok {
		if err := aliassubmissionban.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`pjsk: validator failed for field "AliasSubmissionBan.platform_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BannedBy(); !ok {
		return &ValidationError{Name: "banned_by", err: errors.New(`pjsk: missing required field "AliasSubmissionBan.banned_by"`)}
	}
	if v, ok := _c.mutation.BannedBy(); ok {
		if err := aliassubmissionban.BannedByValidator(v); err != nil {
			return &ValidationError{Name: "banned_by", err: fmt.Errorf(`pjsk: validator failed for field "AliasSubmissionBan.banned_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BannedAt(); !ok {
		return &ValidationError{Name: "banned_at", err: errors.New(`pjsk: missing required field "AliasSubmissionBan.banned_at"`)}
	}
	return nil
}

func (_c *AliasSubmissionBanCreate) sqlSave(ctx context.Context) (*AliasSubmissionBan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AliasSubmissionBanCreate) createSpec() (*AliasSubmissionBan, *sqlgraph.CreateSpec) {
	var (
		_node = &AliasSubmissionBan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aliassubmissionban.Table, sqlgraph.NewFieldSpec(aliassubmissionban.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(aliassubmissionban.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.PlatformUserID(); ok {
		_spec.SetField(aliassubmissionban.FieldPlatformUserID, field.TypeString, value)
		_node.PlatformUserID = value
	}
	if value, ok := _c.mutation.BannedBy(); ok {
		_spec.SetField(aliassubmissionban.FieldBannedBy, field.TypeString, value)
		_node.BannedBy = value
	}
	if value, ok := _c.mutation.BannedAt(); ok {
		_spec.SetField(aliassubmissionban.FieldBannedAt, field.TypeTime, value)
		_node.BannedAt = value
	}
	return _node, _spec
}

// AliasSubmissionBanCreateBulk is the builder for creating many AliasSubmissionBan entities in bulk.
type AliasSubmissionBanCreateBulk struct {
	config
	err      error
	builders []*AliasSubmissionBanCreate
}

// Save creates the AliasSubmissionBan entities in the database.
func (_c *AliasSubmissionBanCreateBulk) Save(ctx context.Context) ([]*AliasSubmissionBan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AliasSubmissionBan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AliasSubmissionBanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AliasSubmissionBanCreateBulk) SaveX(ctx context.Context) []*AliasSubmissionBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AliasSubmissionBanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AliasSubmissionBanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
