sonar.projectKey=Team-Haruki_Haruki-Cloud
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.exclusions=**/*_test.go,database/**/*,ent/**/*,internal/storage/s3/s3test/**/*,internal/storage/storagetest/**/*
sonar.test.inclusions=**/*_test.go

# Written by the go-ci template (coverage-go artifact); sonar.yml passes it on the command line too.
sonar.go.coverage.reportPaths=coverage/go.out
sonar.coverage.exclusions=database/**/*,ent/**/*,internal/storage/s3/s3test/**/*,internal/storage/storagetest/**/*
sonar.cpd.exclusions=database/**/*,ent/**/*
