sonar.projectKey=Team-Haruki_Haruki-Cloud
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.exclusions=**/*_test.go,database/**/*,ent/**/*
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=database/**/*,ent/**/*
sonar.cpd.exclusions=database/**/*,ent/**/*
