// Code generated by ent, DO NOT EDIT.

package aliassubmissionban

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aliassubmissionban type in the database.
	Label = "alias_submission_ban"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformUserID holds the string denoting the platform_user_id field in the database.
	FieldPlatformUserID = "platform_user_id"
	// FieldBannedBy holds the string denoting the banned_by field in the database.
	FieldBannedBy = "banned_by"
	// FieldBannedAt holds the string denoting the banned_at field in the database.
	FieldBannedAt = "banned_at"
	// Table holds the table name of the aliassubmissionban in the database.
	Table = "alias_submission_bans"
)

// Columns holds all SQL columns for aliassubmissionban fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldPlatformUserID,
	FieldBannedBy,
	FieldBannedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// PlatformUserIDValidator is a validator for the "platform_user_id" field. It is called by the builders before save.
	PlatformUserIDValidator func(string) error
	// BannedByValidator is a validator for the "banned_by" field. It is called by the builders before save.
	BannedByValidator func(string) error
)

// OrderOption defines the ordering options for the AliasSubmissionBan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformUserID orders the results by the platform_user_id field.
func ByPlatformUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformUserID, opts...).ToFunc()
}

// ByBannedBy orders the results by the banned_by field.
func ByBannedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBannedBy, opts...).ToFunc()
}

// ByBannedAt orders the results by the banned_at field.
func ByBannedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBannedAt, opts...).ToFunc()
}
