// Code generated by ent_generator. DO NOT EDIT.
package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Areaitemlevel struct {
	ent.Schema
}

func (Areaitemlevel) Fields() []ent.Field {
	return []ent.Field{
		field.Int("area_item_id").Optional(),
		field.Int("level").Optional(),
		field.JSON("target_unit", json.RawMessage{}).Optional(),
		field.JSON("target_card_attr", json.RawMessage{}).Optional(),
		field.Int("target_game_character_id").Optional(),
		field.Float("power1_bonus_rate").Optional(),
		field.Float("power1_all_match_bonus_rate").Optional(),
		field.Float("power2_bonus_rate").Optional(),
		field.Float("power2_all_match_bonus_rate").Optional(),
		field.Float("power3_bonus_rate").Optional(),
		field.Float("power3_all_match_bonus_rate").Optional(),
		field.String("sentence").Optional(),
		field.String("server_region"),
	}
}

func (Areaitemlevel) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "areaitemlevels"},
	}
}

func (Areaitemlevel) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("server_region").Unique(),
	}
}
