// Code generated by ent_generator. DO NOT EDIT.
package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Area struct {
	ent.Schema
}

func (Area) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("game_id"),
		field.String("assetbundle_name").Optional(),
		field.Int64("group_id").Optional(),
		field.Bool("is_base_area").Optional(),
		field.JSON("area_type", json.RawMessage{}).Optional(),
		field.JSON("view_type", json.RawMessage{}).Optional(),
		field.JSON("display_timeline_type", json.RawMessage{}).Optional(),
		field.JSON("additional_area_type", json.RawMessage{}).Optional(),
		field.String("name").Optional(),
		field.Int64("release_condition_id").Optional(),
		field.String("sub_name").Optional(),
		field.String("label").Optional(),
		field.Int64("start_at").Optional(),
		field.Int64("end_at").Optional(),
		field.Int64("release_condition_id2").Optional(),
		field.String("server_region"),
	}
}

func (Area) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "areas"},
	}
}

func (Area) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("game_id", "server_region").Unique(),
	}
}
