// Code generated by ent_generator. DO NOT EDIT.
package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Musicdifficultie struct {
	ent.Schema
}

func (Musicdifficultie) Fields() []ent.Field {
	return []ent.Field{
		field.Int("game_id"),
		field.Int("music_id").Optional(),
		field.JSON("music_difficulty", json.RawMessage{}).Optional(),
		field.Int("play_level").Optional(),
		field.Int("total_note_count").Optional(),
		field.Int("release_condition_id").Optional(),
		field.String("server_region"),
	}
}

func (Musicdifficultie) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "musicdifficulties"},
	}
}

func (Musicdifficultie) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("game_id", "server_region").Unique(),
	}
}
