// Code generated by ent_generator. DO NOT EDIT.
package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Mysekaifixture struct {
	ent.Schema
}

func (Mysekaifixture) Fields() []ent.Field {
	return []ent.Field{
		field.Int("game_id"),
		field.JSON("mysekai_fixture_type", json.RawMessage{}).Optional(),
		field.String("name").Optional(),
		field.String("pronunciation").Optional(),
		field.String("flavor_text").Optional(),
		field.Int("seq").Optional(),
		field.JSON("grid_size", json.RawMessage{}).Optional(),
		field.Int("mysekai_fixture_main_genre_id").Optional(),
		field.Int("mysekai_fixture_sub_genre_id").Optional(),
		field.JSON("mysekai_fixture_handle_type", json.RawMessage{}).Optional(),
		field.JSON("mysekai_settable_site_type", json.RawMessage{}).Optional(),
		field.JSON("mysekai_settable_layout_type", json.RawMessage{}).Optional(),
		field.JSON("mysekai_fixture_put_type", json.RawMessage{}).Optional(),
		field.JSON("mysekai_fixture_another_colors", json.RawMessage{}).Optional(),
		field.Int("mysekai_fixture_put_sound_id").Optional(),
		field.Int("mysekai_fixture_footstep_id").Optional(),
		field.JSON("mysekai_fixture_tag_group", json.RawMessage{}).Optional(),
		field.Bool("is_assembled").Optional(),
		field.Bool("is_disassembled").Optional(),
		field.JSON("mysekai_fixture_player_action_type", json.RawMessage{}).Optional(),
		field.Bool("is_game_character_action").Optional(),
		field.String("assetbundle_name").Optional(),
		field.Int("first_put_cost").Optional(),
		field.Int("second_put_cost").Optional(),
		field.String("color_code").Optional(),
		field.Int("mysekai_fixture_game_character_group_performance_bonus_id").Optional(),
		field.String("server_region"),
	}
}

func (Mysekaifixture) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "mysekaifixtures"},
	}
}

func (Mysekaifixture) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("game_id", "server_region").Unique(),
	}
}
