// Code generated by ent_generator. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Resourceboxdetail struct {
	ent.Schema
}

func (Resourceboxdetail) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("resource_box_id").Optional(),
		field.Int64("resource_quantity").Optional(),
		field.Int64("resource_id").Optional(),
		field.String("resource_box_purpose").Optional(),
		field.Int64("resource_level").Optional(),
		field.String("resource_type").Optional(),
		field.String("server_region"),
	}
}

func (Resourceboxdetail) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "resourceboxdetails"},
	}
}

// Indexes deviates from the Sekai-API generator output: the table has no
// game_id, and Cloud reads it per (region, purpose, box) in insert order, so
// the covering index carries id as its last column. The storage key keeps the
// name under PostgreSQL's 63-byte identifier limit.
func (Resourceboxdetail) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("server_region", "resource_box_purpose", "resource_box_id", "id").
			StorageKey("resourceboxdetail_server_region_purpose_box_id"),
	}
}
