package handler

const (
	rejectAliasUsage              = "使用方式:\n/拒绝别名 待审核ID 原因"
	positivePendingAliasIDMessage = "待审核ID必须为正整数"
	cardBoxCommand                = "card-box"
	cardListCommand               = "card-list"
	deckEventCommand              = "deck-event"
	deckChallengeCommand          = "deck-challenge"
	deckNoEventCommand            = "deck-no-event"
	deckBonusCommand              = "deck-bonus"
	deckMySekaiCommand            = "deck-mysekai"
	educationAreaCommand          = "education-area"
	eventListCommand              = "event-list"
	eventDetailCommand            = "event-detail"
	gachaListCommand              = "gacha-list"
	musicDetailCommand            = "music-detail"
	mySekaiResourceCommand        = "mysekai-resource"
	mySekaiResourceMapCommand     = "mysekai-resource-map"
	mySekaiMapCommand             = "mysekai-map"
	mySekaiFixtureListCommand     = "mysekai-fixture-list"
	mySekaiTalkListCommand        = "mysekai-talk-list"
	mySekaiDoorUpgradeCommand     = "mysekai-door-upgrade"
	mySekaiMusicRecordCommand     = "mysekai-music-record"
	mySekaiPhotoCommand           = "mysekai-photo"
	formattedUsage                = "使用方式:\n%s"
	drawingClientNotConfigured    = "drawing client is not configured"
	pointsPerTimeMetric           = "pt/time"
	skQueryCommand                = "sk-query"
	skCheckRoomCommand            = "sk-check-room"
	skPlayerTraceCommand          = "sk-player-trace"
	stampListCommand              = "stamp-list"
	contextDeadlineExceededText   = "context deadline exceeded"
	clientTimeoutExceededText     = "client.timeout exceeded"
	ioTimeoutText                 = "i/o timeout"
	connectionRefusedText         = "connection refused"
	noSuchHostText                = "no such host"
)
