// Code generated by ent, DO NOT EDIT.

package ngword

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Ngword {
	return predicate.Ngword(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Ngword {
	return predicate.Ngword(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Ngword {
	return predicate.Ngword(sql.FieldLTE(FieldID, id))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldServerRegion, v))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldGameID, v))
}

// Word applies equality check predicate on the "word" field. It's identical to WordEQ.
func Word(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldWord, v))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Ngword {
	return predicate.Ngword(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Ngword {
	return predicate.Ngword(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldContainsFold(FieldServerRegion, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v int64) predicate.Ngword {
	return predicate.Ngword(sql.FieldLTE(FieldGameID, v))
}

// GameIDIsNil applies the IsNil predicate on the "game_id" field.
func GameIDIsNil() predicate.Ngword {
	return predicate.Ngword(sql.FieldIsNull(FieldGameID))
}

// GameIDNotNil applies the NotNil predicate on the "game_id" field.
func GameIDNotNil() predicate.Ngword {
	return predicate.Ngword(sql.FieldNotNull(FieldGameID))
}

// WordEQ applies the EQ predicate on the "word" field.
func WordEQ(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEQ(FieldWord, v))
}

// WordNEQ applies the NEQ predicate on the "word" field.
func WordNEQ(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldNEQ(FieldWord, v))
}

// WordIn applies the In predicate on the "word" field.
func WordIn(vs ...string) predicate.Ngword {
	return predicate.Ngword(sql.FieldIn(FieldWord, vs...))
}

// WordNotIn applies the NotIn predicate on the "word" field.
func WordNotIn(vs ...string) predicate.Ngword {
	return predicate.Ngword(sql.FieldNotIn(FieldWord, vs...))
}

// WordGT applies the GT predicate on the "word" field.
func WordGT(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldGT(FieldWord, v))
}

// WordGTE applies the GTE predicate on the "word" field.
func WordGTE(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldGTE(FieldWord, v))
}

// WordLT applies the LT predicate on the "word" field.
func WordLT(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldLT(FieldWord, v))
}

// WordLTE applies the LTE predicate on the "word" field.
func WordLTE(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldLTE(FieldWord, v))
}

// WordContains applies the Contains predicate on the "word" field.
func WordContains(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldContains(FieldWord, v))
}

// WordHasPrefix applies the HasPrefix predicate on the "word" field.
func WordHasPrefix(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldHasPrefix(FieldWord, v))
}

// WordHasSuffix applies the HasSuffix predicate on the "word" field.
func WordHasSuffix(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldHasSuffix(FieldWord, v))
}

// WordIsNil applies the IsNil predicate on the "word" field.
func WordIsNil() predicate.Ngword {
	return predicate.Ngword(sql.FieldIsNull(FieldWord))
}

// WordNotNil applies the NotNil predicate on the "word" field.
func WordNotNil() predicate.Ngword {
	return predicate.Ngword(sql.FieldNotNull(FieldWord))
}

// WordEqualFold applies the EqualFold predicate on the "word" field.
func WordEqualFold(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldEqualFold(FieldWord, v))
}

// WordContainsFold applies the ContainsFold predicate on the "word" field.
func WordContainsFold(v string) predicate.Ngword {
	return predicate.Ngword(sql.FieldContainsFold(FieldWord, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ngword) predicate.Ngword {
	return predicate.Ngword(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ngword) predicate.Ngword {
	return predicate.Ngword(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ngword) predicate.Ngword {
	return predicate.Ngword(sql.NotPredicates(p))
}
