// Code generated by ent, DO NOT EDIT.

package gamecharacter

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGameID, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldSeq, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldResourceID, v))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstName, v))
}

// GivenName applies equality check predicate on the "given_name" field. It's identical to GivenNameEQ.
func GivenName(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenName, v))
}

// FirstNameRuby applies equality check predicate on the "first_name_ruby" field. It's identical to FirstNameRubyEQ.
func FirstNameRuby(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstNameRuby, v))
}

// GivenNameRuby applies equality check predicate on the "given_name_ruby" field. It's identical to GivenNameRubyEQ.
func GivenNameRuby(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenNameRuby, v))
}

// FirstNameEnglish applies equality check predicate on the "first_name_english" field. It's identical to FirstNameEnglishEQ.
func FirstNameEnglish(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstNameEnglish, v))
}

// GivenNameEnglish applies equality check predicate on the "given_name_english" field. It's identical to GivenNameEnglishEQ.
func GivenNameEnglish(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenNameEnglish, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldHeight, v))
}

// Live2DHeightAdjustment applies equality check predicate on the "live2_d_height_adjustment" field. It's identical to Live2DHeightAdjustmentEQ.
func Live2DHeightAdjustment(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldLive2DHeightAdjustment, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldModelName, v))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldServerRegion, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldGameID, v))
}

// GameIDIsNil applies the IsNil predicate on the "game_id" field.
func GameIDIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldGameID))
}

// GameIDNotNil applies the NotNil predicate on the "game_id" field.
func GameIDNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldGameID))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldSeq, v))
}

// SeqIsNil applies the IsNil predicate on the "seq" field.
func SeqIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldSeq))
}

// SeqNotNil applies the NotNil predicate on the "seq" field.
func SeqNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldSeq))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v int64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDIsNil applies the IsNil predicate on the "resource_id" field.
func ResourceIDIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldResourceID))
}

// ResourceIDNotNil applies the NotNil predicate on the "resource_id" field.
func ResourceIDNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldResourceID))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameIsNil applies the IsNil predicate on the "first_name" field.
func FirstNameIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldFirstName))
}

// FirstNameNotNil applies the NotNil predicate on the "first_name" field.
func FirstNameNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldFirstName))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldFirstName, v))
}

// GivenNameEQ applies the EQ predicate on the "given_name" field.
func GivenNameEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenName, v))
}

// GivenNameNEQ applies the NEQ predicate on the "given_name" field.
func GivenNameNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldGivenName, v))
}

// GivenNameIn applies the In predicate on the "given_name" field.
func GivenNameIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldGivenName, vs...))
}

// GivenNameNotIn applies the NotIn predicate on the "given_name" field.
func GivenNameNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldGivenName, vs...))
}

// GivenNameGT applies the GT predicate on the "given_name" field.
func GivenNameGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldGivenName, v))
}

// GivenNameGTE applies the GTE predicate on the "given_name" field.
func GivenNameGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldGivenName, v))
}

// GivenNameLT applies the LT predicate on the "given_name" field.
func GivenNameLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldGivenName, v))
}

// GivenNameLTE applies the LTE predicate on the "given_name" field.
func GivenNameLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldGivenName, v))
}

// GivenNameContains applies the Contains predicate on the "given_name" field.
func GivenNameContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldGivenName, v))
}

// GivenNameHasPrefix applies the HasPrefix predicate on the "given_name" field.
func GivenNameHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldGivenName, v))
}

// GivenNameHasSuffix applies the HasSuffix predicate on the "given_name" field.
func GivenNameHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldGivenName, v))
}

// GivenNameIsNil applies the IsNil predicate on the "given_name" field.
func GivenNameIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldGivenName))
}

// GivenNameNotNil applies the NotNil predicate on the "given_name" field.
func GivenNameNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldGivenName))
}

// GivenNameEqualFold applies the EqualFold predicate on the "given_name" field.
func GivenNameEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldGivenName, v))
}

// GivenNameContainsFold applies the ContainsFold predicate on the "given_name" field.
func GivenNameContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldGivenName, v))
}

// FirstNameRubyEQ applies the EQ predicate on the "first_name_ruby" field.
func FirstNameRubyEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstNameRuby, v))
}

// FirstNameRubyNEQ applies the NEQ predicate on the "first_name_ruby" field.
func FirstNameRubyNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldFirstNameRuby, v))
}

// FirstNameRubyIn applies the In predicate on the "first_name_ruby" field.
func FirstNameRubyIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldFirstNameRuby, vs...))
}

// FirstNameRubyNotIn applies the NotIn predicate on the "first_name_ruby" field.
func FirstNameRubyNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldFirstNameRuby, vs...))
}

// FirstNameRubyGT applies the GT predicate on the "first_name_ruby" field.
func FirstNameRubyGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldFirstNameRuby, v))
}

// FirstNameRubyGTE applies the GTE predicate on the "first_name_ruby" field.
func FirstNameRubyGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldFirstNameRuby, v))
}

// FirstNameRubyLT applies the LT predicate on the "first_name_ruby" field.
func FirstNameRubyLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldFirstNameRuby, v))
}

// FirstNameRubyLTE applies the LTE predicate on the "first_name_ruby" field.
func FirstNameRubyLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldFirstNameRuby, v))
}

// FirstNameRubyContains applies the Contains predicate on the "first_name_ruby" field.
func FirstNameRubyContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldFirstNameRuby, v))
}

// FirstNameRubyHasPrefix applies the HasPrefix predicate on the "first_name_ruby" field.
func FirstNameRubyHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldFirstNameRuby, v))
}

// FirstNameRubyHasSuffix applies the HasSuffix predicate on the "first_name_ruby" field.
func FirstNameRubyHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldFirstNameRuby, v))
}

// FirstNameRubyIsNil applies the IsNil predicate on the "first_name_ruby" field.
func FirstNameRubyIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldFirstNameRuby))
}

// FirstNameRubyNotNil applies the NotNil predicate on the "first_name_ruby" field.
func FirstNameRubyNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldFirstNameRuby))
}

// FirstNameRubyEqualFold applies the EqualFold predicate on the "first_name_ruby" field.
func FirstNameRubyEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldFirstNameRuby, v))
}

// FirstNameRubyContainsFold applies the ContainsFold predicate on the "first_name_ruby" field.
func FirstNameRubyContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldFirstNameRuby, v))
}

// GivenNameRubyEQ applies the EQ predicate on the "given_name_ruby" field.
func GivenNameRubyEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenNameRuby, v))
}

// GivenNameRubyNEQ applies the NEQ predicate on the "given_name_ruby" field.
func GivenNameRubyNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldGivenNameRuby, v))
}

// GivenNameRubyIn applies the In predicate on the "given_name_ruby" field.
func GivenNameRubyIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldGivenNameRuby, vs...))
}

// GivenNameRubyNotIn applies the NotIn predicate on the "given_name_ruby" field.
func GivenNameRubyNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldGivenNameRuby, vs...))
}

// GivenNameRubyGT applies the GT predicate on the "given_name_ruby" field.
func GivenNameRubyGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldGivenNameRuby, v))
}

// GivenNameRubyGTE applies the GTE predicate on the "given_name_ruby" field.
func GivenNameRubyGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldGivenNameRuby, v))
}

// GivenNameRubyLT applies the LT predicate on the "given_name_ruby" field.
func GivenNameRubyLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldGivenNameRuby, v))
}

// GivenNameRubyLTE applies the LTE predicate on the "given_name_ruby" field.
func GivenNameRubyLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldGivenNameRuby, v))
}

// GivenNameRubyContains applies the Contains predicate on the "given_name_ruby" field.
func GivenNameRubyContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldGivenNameRuby, v))
}

// GivenNameRubyHasPrefix applies the HasPrefix predicate on the "given_name_ruby" field.
func GivenNameRubyHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldGivenNameRuby, v))
}

// GivenNameRubyHasSuffix applies the HasSuffix predicate on the "given_name_ruby" field.
func GivenNameRubyHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldGivenNameRuby, v))
}

// GivenNameRubyIsNil applies the IsNil predicate on the "given_name_ruby" field.
func GivenNameRubyIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldGivenNameRuby))
}

// GivenNameRubyNotNil applies the NotNil predicate on the "given_name_ruby" field.
func GivenNameRubyNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldGivenNameRuby))
}

// GivenNameRubyEqualFold applies the EqualFold predicate on the "given_name_ruby" field.
func GivenNameRubyEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldGivenNameRuby, v))
}

// GivenNameRubyContainsFold applies the ContainsFold predicate on the "given_name_ruby" field.
func GivenNameRubyContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldGivenNameRuby, v))
}

// FirstNameEnglishEQ applies the EQ predicate on the "first_name_english" field.
func FirstNameEnglishEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldFirstNameEnglish, v))
}

// FirstNameEnglishNEQ applies the NEQ predicate on the "first_name_english" field.
func FirstNameEnglishNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldFirstNameEnglish, v))
}

// FirstNameEnglishIn applies the In predicate on the "first_name_english" field.
func FirstNameEnglishIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldFirstNameEnglish, vs...))
}

// FirstNameEnglishNotIn applies the NotIn predicate on the "first_name_english" field.
func FirstNameEnglishNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldFirstNameEnglish, vs...))
}

// FirstNameEnglishGT applies the GT predicate on the "first_name_english" field.
func FirstNameEnglishGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldFirstNameEnglish, v))
}

// FirstNameEnglishGTE applies the GTE predicate on the "first_name_english" field.
func FirstNameEnglishGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldFirstNameEnglish, v))
}

// FirstNameEnglishLT applies the LT predicate on the "first_name_english" field.
func FirstNameEnglishLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldFirstNameEnglish, v))
}

// FirstNameEnglishLTE applies the LTE predicate on the "first_name_english" field.
func FirstNameEnglishLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldFirstNameEnglish, v))
}

// FirstNameEnglishContains applies the Contains predicate on the "first_name_english" field.
func FirstNameEnglishContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldFirstNameEnglish, v))
}

// FirstNameEnglishHasPrefix applies the HasPrefix predicate on the "first_name_english" field.
func FirstNameEnglishHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldFirstNameEnglish, v))
}

// FirstNameEnglishHasSuffix applies the HasSuffix predicate on the "first_name_english" field.
func FirstNameEnglishHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldFirstNameEnglish, v))
}

// FirstNameEnglishIsNil applies the IsNil predicate on the "first_name_english" field.
func FirstNameEnglishIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldFirstNameEnglish))
}

// FirstNameEnglishNotNil applies the NotNil predicate on the "first_name_english" field.
func FirstNameEnglishNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldFirstNameEnglish))
}

// FirstNameEnglishEqualFold applies the EqualFold predicate on the "first_name_english" field.
func FirstNameEnglishEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldFirstNameEnglish, v))
}

// FirstNameEnglishContainsFold applies the ContainsFold predicate on the "first_name_english" field.
func FirstNameEnglishContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldFirstNameEnglish, v))
}

// GivenNameEnglishEQ applies the EQ predicate on the "given_name_english" field.
func GivenNameEnglishEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldGivenNameEnglish, v))
}

// GivenNameEnglishNEQ applies the NEQ predicate on the "given_name_english" field.
func GivenNameEnglishNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldGivenNameEnglish, v))
}

// GivenNameEnglishIn applies the In predicate on the "given_name_english" field.
func GivenNameEnglishIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldGivenNameEnglish, vs...))
}

// GivenNameEnglishNotIn applies the NotIn predicate on the "given_name_english" field.
func GivenNameEnglishNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldGivenNameEnglish, vs...))
}

// GivenNameEnglishGT applies the GT predicate on the "given_name_english" field.
func GivenNameEnglishGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldGivenNameEnglish, v))
}

// GivenNameEnglishGTE applies the GTE predicate on the "given_name_english" field.
func GivenNameEnglishGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldGivenNameEnglish, v))
}

// GivenNameEnglishLT applies the LT predicate on the "given_name_english" field.
func GivenNameEnglishLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldGivenNameEnglish, v))
}

// GivenNameEnglishLTE applies the LTE predicate on the "given_name_english" field.
func GivenNameEnglishLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldGivenNameEnglish, v))
}

// GivenNameEnglishContains applies the Contains predicate on the "given_name_english" field.
func GivenNameEnglishContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldGivenNameEnglish, v))
}

// GivenNameEnglishHasPrefix applies the HasPrefix predicate on the "given_name_english" field.
func GivenNameEnglishHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldGivenNameEnglish, v))
}

// GivenNameEnglishHasSuffix applies the HasSuffix predicate on the "given_name_english" field.
func GivenNameEnglishHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldGivenNameEnglish, v))
}

// GivenNameEnglishIsNil applies the IsNil predicate on the "given_name_english" field.
func GivenNameEnglishIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldGivenNameEnglish))
}

// GivenNameEnglishNotNil applies the NotNil predicate on the "given_name_english" field.
func GivenNameEnglishNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldGivenNameEnglish))
}

// GivenNameEnglishEqualFold applies the EqualFold predicate on the "given_name_english" field.
func GivenNameEnglishEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldGivenNameEnglish, v))
}

// GivenNameEnglishContainsFold applies the ContainsFold predicate on the "given_name_english" field.
func GivenNameEnglishContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldGivenNameEnglish, v))
}

// GenderIsNil applies the IsNil predicate on the "gender" field.
func GenderIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldGender))
}

// GenderNotNil applies the NotNil predicate on the "gender" field.
func GenderNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldGender))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldHeight))
}

// Live2DHeightAdjustmentEQ applies the EQ predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentEQ(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentNEQ applies the NEQ predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentNEQ(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentIn applies the In predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentIn(vs ...float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldLive2DHeightAdjustment, vs...))
}

// Live2DHeightAdjustmentNotIn applies the NotIn predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentNotIn(vs ...float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldLive2DHeightAdjustment, vs...))
}

// Live2DHeightAdjustmentGT applies the GT predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentGT(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentGTE applies the GTE predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentGTE(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentLT applies the LT predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentLT(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentLTE applies the LTE predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentLTE(v float64) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldLive2DHeightAdjustment, v))
}

// Live2DHeightAdjustmentIsNil applies the IsNil predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldLive2DHeightAdjustment))
}

// Live2DHeightAdjustmentNotNil applies the NotNil predicate on the "live2_d_height_adjustment" field.
func Live2DHeightAdjustmentNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldLive2DHeightAdjustment))
}

// FigureIsNil applies the IsNil predicate on the "figure" field.
func FigureIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldFigure))
}

// FigureNotNil applies the NotNil predicate on the "figure" field.
func FigureNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldFigure))
}

// BreastSizeIsNil applies the IsNil predicate on the "breast_size" field.
func BreastSizeIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldBreastSize))
}

// BreastSizeNotNil applies the NotNil predicate on the "breast_size" field.
func BreastSizeNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldBreastSize))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameIsNil applies the IsNil predicate on the "model_name" field.
func ModelNameIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldModelName))
}

// ModelNameNotNil applies the NotNil predicate on the "model_name" field.
func ModelNameNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldModelName))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldModelName, v))
}

// UnitIsNil applies the IsNil predicate on the "unit" field.
func UnitIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldUnit))
}

// UnitNotNil applies the NotNil predicate on the "unit" field.
func UnitNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldUnit))
}

// SupportUnitTypeIsNil applies the IsNil predicate on the "support_unit_type" field.
func SupportUnitTypeIsNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIsNull(FieldSupportUnitType))
}

// SupportUnitTypeNotNil applies the NotNil predicate on the "support_unit_type" field.
func SupportUnitTypeNotNil() predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotNull(FieldSupportUnitType))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.FieldContainsFold(FieldServerRegion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Gamecharacter) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Gamecharacter) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Gamecharacter) predicate.Gamecharacter {
	return predicate.Gamecharacter(sql.NotPredicates(p))
}
