// Code generated by ent, DO NOT EDIT.

package customprofilecharactericonresource

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldID, id))
}

// CustomProfileResourceType applies equality check predicate on the "custom_profile_resource_type" field. It's identical to CustomProfileResourceTypeEQ.
func CustomProfileResourceType(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldCustomProfileResourceType, v))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldGameID, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldSeq, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldName, v))
}

// Pronunciation applies equality check predicate on the "pronunciation" field. It's identical to PronunciationEQ.
func Pronunciation(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldPronunciation, v))
}

// ResourceLoadType applies equality check predicate on the "resource_load_type" field. It's identical to ResourceLoadTypeEQ.
func ResourceLoadType(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldResourceLoadType, v))
}

// ResourceLoadVal applies equality check predicate on the "resource_load_val" field. It's identical to ResourceLoadValEQ.
func ResourceLoadVal(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldResourceLoadVal, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldFileName, v))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldServerRegion, v))
}

// CustomProfileResourceTypeEQ applies the EQ predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeNEQ applies the NEQ predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeIn applies the In predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldCustomProfileResourceType, vs...))
}

// CustomProfileResourceTypeNotIn applies the NotIn predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldCustomProfileResourceType, vs...))
}

// CustomProfileResourceTypeGT applies the GT predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeGTE applies the GTE predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeLT applies the LT predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeLTE applies the LTE predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeContains applies the Contains predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeHasPrefix applies the HasPrefix predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeHasSuffix applies the HasSuffix predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeIsNil applies the IsNil predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldCustomProfileResourceType))
}

// CustomProfileResourceTypeNotNil applies the NotNil predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldCustomProfileResourceType))
}

// CustomProfileResourceTypeEqualFold applies the EqualFold predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldCustomProfileResourceType, v))
}

// CustomProfileResourceTypeContainsFold applies the ContainsFold predicate on the "custom_profile_resource_type" field.
func CustomProfileResourceTypeContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldCustomProfileResourceType, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldGameID, v))
}

// GameIDIsNil applies the IsNil predicate on the "game_id" field.
func GameIDIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldGameID))
}

// GameIDNotNil applies the NotNil predicate on the "game_id" field.
func GameIDNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldGameID))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int64) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldSeq, v))
}

// SeqIsNil applies the IsNil predicate on the "seq" field.
func SeqIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldSeq))
}

// SeqNotNil applies the NotNil predicate on the "seq" field.
func SeqNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldSeq))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldName, v))
}

// PronunciationEQ applies the EQ predicate on the "pronunciation" field.
func PronunciationEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldPronunciation, v))
}

// PronunciationNEQ applies the NEQ predicate on the "pronunciation" field.
func PronunciationNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldPronunciation, v))
}

// PronunciationIn applies the In predicate on the "pronunciation" field.
func PronunciationIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldPronunciation, vs...))
}

// PronunciationNotIn applies the NotIn predicate on the "pronunciation" field.
func PronunciationNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldPronunciation, vs...))
}

// PronunciationGT applies the GT predicate on the "pronunciation" field.
func PronunciationGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldPronunciation, v))
}

// PronunciationGTE applies the GTE predicate on the "pronunciation" field.
func PronunciationGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldPronunciation, v))
}

// PronunciationLT applies the LT predicate on the "pronunciation" field.
func PronunciationLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldPronunciation, v))
}

// PronunciationLTE applies the LTE predicate on the "pronunciation" field.
func PronunciationLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldPronunciation, v))
}

// PronunciationContains applies the Contains predicate on the "pronunciation" field.
func PronunciationContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldPronunciation, v))
}

// PronunciationHasPrefix applies the HasPrefix predicate on the "pronunciation" field.
func PronunciationHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldPronunciation, v))
}

// PronunciationHasSuffix applies the HasSuffix predicate on the "pronunciation" field.
func PronunciationHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldPronunciation, v))
}

// PronunciationIsNil applies the IsNil predicate on the "pronunciation" field.
func PronunciationIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldPronunciation))
}

// PronunciationNotNil applies the NotNil predicate on the "pronunciation" field.
func PronunciationNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldPronunciation))
}

// PronunciationEqualFold applies the EqualFold predicate on the "pronunciation" field.
func PronunciationEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldPronunciation, v))
}

// PronunciationContainsFold applies the ContainsFold predicate on the "pronunciation" field.
func PronunciationContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldPronunciation, v))
}

// ResourceLoadTypeEQ applies the EQ predicate on the "resource_load_type" field.
func ResourceLoadTypeEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldResourceLoadType, v))
}

// ResourceLoadTypeNEQ applies the NEQ predicate on the "resource_load_type" field.
func ResourceLoadTypeNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldResourceLoadType, v))
}

// ResourceLoadTypeIn applies the In predicate on the "resource_load_type" field.
func ResourceLoadTypeIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldResourceLoadType, vs...))
}

// ResourceLoadTypeNotIn applies the NotIn predicate on the "resource_load_type" field.
func ResourceLoadTypeNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldResourceLoadType, vs...))
}

// ResourceLoadTypeGT applies the GT predicate on the "resource_load_type" field.
func ResourceLoadTypeGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldResourceLoadType, v))
}

// ResourceLoadTypeGTE applies the GTE predicate on the "resource_load_type" field.
func ResourceLoadTypeGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldResourceLoadType, v))
}

// ResourceLoadTypeLT applies the LT predicate on the "resource_load_type" field.
func ResourceLoadTypeLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldResourceLoadType, v))
}

// ResourceLoadTypeLTE applies the LTE predicate on the "resource_load_type" field.
func ResourceLoadTypeLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldResourceLoadType, v))
}

// ResourceLoadTypeContains applies the Contains predicate on the "resource_load_type" field.
func ResourceLoadTypeContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldResourceLoadType, v))
}

// ResourceLoadTypeHasPrefix applies the HasPrefix predicate on the "resource_load_type" field.
func ResourceLoadTypeHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldResourceLoadType, v))
}

// ResourceLoadTypeHasSuffix applies the HasSuffix predicate on the "resource_load_type" field.
func ResourceLoadTypeHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldResourceLoadType, v))
}

// ResourceLoadTypeIsNil applies the IsNil predicate on the "resource_load_type" field.
func ResourceLoadTypeIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldResourceLoadType))
}

// ResourceLoadTypeNotNil applies the NotNil predicate on the "resource_load_type" field.
func ResourceLoadTypeNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldResourceLoadType))
}

// ResourceLoadTypeEqualFold applies the EqualFold predicate on the "resource_load_type" field.
func ResourceLoadTypeEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldResourceLoadType, v))
}

// ResourceLoadTypeContainsFold applies the ContainsFold predicate on the "resource_load_type" field.
func ResourceLoadTypeContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldResourceLoadType, v))
}

// ResourceLoadValEQ applies the EQ predicate on the "resource_load_val" field.
func ResourceLoadValEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldResourceLoadVal, v))
}

// ResourceLoadValNEQ applies the NEQ predicate on the "resource_load_val" field.
func ResourceLoadValNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldResourceLoadVal, v))
}

// ResourceLoadValIn applies the In predicate on the "resource_load_val" field.
func ResourceLoadValIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldResourceLoadVal, vs...))
}

// ResourceLoadValNotIn applies the NotIn predicate on the "resource_load_val" field.
func ResourceLoadValNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldResourceLoadVal, vs...))
}

// ResourceLoadValGT applies the GT predicate on the "resource_load_val" field.
func ResourceLoadValGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldResourceLoadVal, v))
}

// ResourceLoadValGTE applies the GTE predicate on the "resource_load_val" field.
func ResourceLoadValGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldResourceLoadVal, v))
}

// ResourceLoadValLT applies the LT predicate on the "resource_load_val" field.
func ResourceLoadValLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldResourceLoadVal, v))
}

// ResourceLoadValLTE applies the LTE predicate on the "resource_load_val" field.
func ResourceLoadValLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldResourceLoadVal, v))
}

// ResourceLoadValContains applies the Contains predicate on the "resource_load_val" field.
func ResourceLoadValContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldResourceLoadVal, v))
}

// ResourceLoadValHasPrefix applies the HasPrefix predicate on the "resource_load_val" field.
func ResourceLoadValHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldResourceLoadVal, v))
}

// ResourceLoadValHasSuffix applies the HasSuffix predicate on the "resource_load_val" field.
func ResourceLoadValHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldResourceLoadVal, v))
}

// ResourceLoadValIsNil applies the IsNil predicate on the "resource_load_val" field.
func ResourceLoadValIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldResourceLoadVal))
}

// ResourceLoadValNotNil applies the NotNil predicate on the "resource_load_val" field.
func ResourceLoadValNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldResourceLoadVal))
}

// ResourceLoadValEqualFold applies the EqualFold predicate on the "resource_load_val" field.
func ResourceLoadValEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldResourceLoadVal, v))
}

// ResourceLoadValContainsFold applies the ContainsFold predicate on the "resource_load_val" field.
func ResourceLoadValContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldResourceLoadVal, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameIsNil applies the IsNil predicate on the "file_name" field.
func FileNameIsNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIsNull(FieldFileName))
}

// FileNameNotNil applies the NotNil predicate on the "file_name" field.
func FileNameNotNil() predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotNull(FieldFileName))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldFileName, v))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.FieldContainsFold(FieldServerRegion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Customprofilecharactericonresource) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Customprofilecharactericonresource) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Customprofilecharactericonresource) predicate.Customprofilecharactericonresource {
	return predicate.Customprofilecharactericonresource(sql.NotPredicates(p))
}
