// Code generated by ent, DO NOT EDIT.

package mysekaisiteharvestfixture

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldGameID, v))
}

// MysekaiSiteHarvestFixtureType applies equality check predicate on the "mysekai_site_harvest_fixture_type" field. It's identical to MysekaiSiteHarvestFixtureTypeEQ.
func MysekaiSiteHarvestFixtureType(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldMysekaiSiteHarvestFixtureType, v))
}

// Hp applies equality check predicate on the "hp" field. It's identical to HpEQ.
func Hp(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldHp, v))
}

// LastAttackStamina applies equality check predicate on the "last_attack_stamina" field. It's identical to LastAttackStaminaEQ.
func LastAttackStamina(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldLastAttackStamina, v))
}

// AssetbundleName applies equality check predicate on the "assetbundle_name" field. It's identical to AssetbundleNameEQ.
func AssetbundleName(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldAssetbundleName, v))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldServerRegion, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldGameID, v))
}

// MysekaiSiteHarvestFixtureTypeEQ applies the EQ predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeNEQ applies the NEQ predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeNEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeIn applies the In predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldMysekaiSiteHarvestFixtureType, vs...))
}

// MysekaiSiteHarvestFixtureTypeNotIn applies the NotIn predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeNotIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldMysekaiSiteHarvestFixtureType, vs...))
}

// MysekaiSiteHarvestFixtureTypeGT applies the GT predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeGT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeGTE applies the GTE predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeGTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeLT applies the LT predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeLT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeLTE applies the LTE predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeLTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeContains applies the Contains predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeContains(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContains(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeHasPrefix applies the HasPrefix predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeHasPrefix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasPrefix(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeHasSuffix applies the HasSuffix predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeHasSuffix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasSuffix(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeIsNil applies the IsNil predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeIsNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIsNull(FieldMysekaiSiteHarvestFixtureType))
}

// MysekaiSiteHarvestFixtureTypeNotNil applies the NotNil predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeNotNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotNull(FieldMysekaiSiteHarvestFixtureType))
}

// MysekaiSiteHarvestFixtureTypeEqualFold applies the EqualFold predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeEqualFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEqualFold(FieldMysekaiSiteHarvestFixtureType, v))
}

// MysekaiSiteHarvestFixtureTypeContainsFold applies the ContainsFold predicate on the "mysekai_site_harvest_fixture_type" field.
func MysekaiSiteHarvestFixtureTypeContainsFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContainsFold(FieldMysekaiSiteHarvestFixtureType, v))
}

// HpEQ applies the EQ predicate on the "hp" field.
func HpEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldHp, v))
}

// HpNEQ applies the NEQ predicate on the "hp" field.
func HpNEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldHp, v))
}

// HpIn applies the In predicate on the "hp" field.
func HpIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldHp, vs...))
}

// HpNotIn applies the NotIn predicate on the "hp" field.
func HpNotIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldHp, vs...))
}

// HpGT applies the GT predicate on the "hp" field.
func HpGT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldHp, v))
}

// HpGTE applies the GTE predicate on the "hp" field.
func HpGTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldHp, v))
}

// HpLT applies the LT predicate on the "hp" field.
func HpLT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldHp, v))
}

// HpLTE applies the LTE predicate on the "hp" field.
func HpLTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldHp, v))
}

// HpIsNil applies the IsNil predicate on the "hp" field.
func HpIsNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIsNull(FieldHp))
}

// HpNotNil applies the NotNil predicate on the "hp" field.
func HpNotNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotNull(FieldHp))
}

// LastAttackStaminaEQ applies the EQ predicate on the "last_attack_stamina" field.
func LastAttackStaminaEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldLastAttackStamina, v))
}

// LastAttackStaminaNEQ applies the NEQ predicate on the "last_attack_stamina" field.
func LastAttackStaminaNEQ(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldLastAttackStamina, v))
}

// LastAttackStaminaIn applies the In predicate on the "last_attack_stamina" field.
func LastAttackStaminaIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldLastAttackStamina, vs...))
}

// LastAttackStaminaNotIn applies the NotIn predicate on the "last_attack_stamina" field.
func LastAttackStaminaNotIn(vs ...int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldLastAttackStamina, vs...))
}

// LastAttackStaminaGT applies the GT predicate on the "last_attack_stamina" field.
func LastAttackStaminaGT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldLastAttackStamina, v))
}

// LastAttackStaminaGTE applies the GTE predicate on the "last_attack_stamina" field.
func LastAttackStaminaGTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldLastAttackStamina, v))
}

// LastAttackStaminaLT applies the LT predicate on the "last_attack_stamina" field.
func LastAttackStaminaLT(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldLastAttackStamina, v))
}

// LastAttackStaminaLTE applies the LTE predicate on the "last_attack_stamina" field.
func LastAttackStaminaLTE(v int) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldLastAttackStamina, v))
}

// LastAttackStaminaIsNil applies the IsNil predicate on the "last_attack_stamina" field.
func LastAttackStaminaIsNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIsNull(FieldLastAttackStamina))
}

// LastAttackStaminaNotNil applies the NotNil predicate on the "last_attack_stamina" field.
func LastAttackStaminaNotNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotNull(FieldLastAttackStamina))
}

// MysekaiSiteHarvestFixtureRarityTypeIsNil applies the IsNil predicate on the "mysekai_site_harvest_fixture_rarity_type" field.
func MysekaiSiteHarvestFixtureRarityTypeIsNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIsNull(FieldMysekaiSiteHarvestFixtureRarityType))
}

// MysekaiSiteHarvestFixtureRarityTypeNotNil applies the NotNil predicate on the "mysekai_site_harvest_fixture_rarity_type" field.
func MysekaiSiteHarvestFixtureRarityTypeNotNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotNull(FieldMysekaiSiteHarvestFixtureRarityType))
}

// AssetbundleNameEQ applies the EQ predicate on the "assetbundle_name" field.
func AssetbundleNameEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldAssetbundleName, v))
}

// AssetbundleNameNEQ applies the NEQ predicate on the "assetbundle_name" field.
func AssetbundleNameNEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldAssetbundleName, v))
}

// AssetbundleNameIn applies the In predicate on the "assetbundle_name" field.
func AssetbundleNameIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldAssetbundleName, vs...))
}

// AssetbundleNameNotIn applies the NotIn predicate on the "assetbundle_name" field.
func AssetbundleNameNotIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldAssetbundleName, vs...))
}

// AssetbundleNameGT applies the GT predicate on the "assetbundle_name" field.
func AssetbundleNameGT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldAssetbundleName, v))
}

// AssetbundleNameGTE applies the GTE predicate on the "assetbundle_name" field.
func AssetbundleNameGTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldAssetbundleName, v))
}

// AssetbundleNameLT applies the LT predicate on the "assetbundle_name" field.
func AssetbundleNameLT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldAssetbundleName, v))
}

// AssetbundleNameLTE applies the LTE predicate on the "assetbundle_name" field.
func AssetbundleNameLTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldAssetbundleName, v))
}

// AssetbundleNameContains applies the Contains predicate on the "assetbundle_name" field.
func AssetbundleNameContains(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContains(FieldAssetbundleName, v))
}

// AssetbundleNameHasPrefix applies the HasPrefix predicate on the "assetbundle_name" field.
func AssetbundleNameHasPrefix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasPrefix(FieldAssetbundleName, v))
}

// AssetbundleNameHasSuffix applies the HasSuffix predicate on the "assetbundle_name" field.
func AssetbundleNameHasSuffix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasSuffix(FieldAssetbundleName, v))
}

// AssetbundleNameIsNil applies the IsNil predicate on the "assetbundle_name" field.
func AssetbundleNameIsNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIsNull(FieldAssetbundleName))
}

// AssetbundleNameNotNil applies the NotNil predicate on the "assetbundle_name" field.
func AssetbundleNameNotNil() predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotNull(FieldAssetbundleName))
}

// AssetbundleNameEqualFold applies the EqualFold predicate on the "assetbundle_name" field.
func AssetbundleNameEqualFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEqualFold(FieldAssetbundleName, v))
}

// AssetbundleNameContainsFold applies the ContainsFold predicate on the "assetbundle_name" field.
func AssetbundleNameContainsFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContainsFold(FieldAssetbundleName, v))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.FieldContainsFold(FieldServerRegion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Mysekaisiteharvestfixture) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Mysekaisiteharvestfixture) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Mysekaisiteharvestfixture) predicate.Mysekaisiteharvestfixture {
	return predicate.Mysekaisiteharvestfixture(sql.NotPredicates(p))
}
