// Code generated by ent, DO NOT EDIT.

package musicvocal

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldGameID, v))
}

// MusicID applies equality check predicate on the "music_id" field. It's identical to MusicIDEQ.
func MusicID(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldMusicID, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldSeq, v))
}

// ReleaseConditionID applies equality check predicate on the "release_condition_id" field. It's identical to ReleaseConditionIDEQ.
func ReleaseConditionID(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldReleaseConditionID, v))
}

// Caption applies equality check predicate on the "caption" field. It's identical to CaptionEQ.
func Caption(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldCaption, v))
}

// AssetbundleName applies equality check predicate on the "assetbundle_name" field. It's identical to AssetbundleNameEQ.
func AssetbundleName(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldAssetbundleName, v))
}

// ArchivePublishedAt applies equality check predicate on the "archive_published_at" field. It's identical to ArchivePublishedAtEQ.
func ArchivePublishedAt(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldArchivePublishedAt, v))
}

// SpecialSeasonID applies equality check predicate on the "special_season_id" field. It's identical to SpecialSeasonIDEQ.
func SpecialSeasonID(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldSpecialSeasonID, v))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldServerRegion, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldGameID, v))
}

// MusicIDEQ applies the EQ predicate on the "music_id" field.
func MusicIDEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldMusicID, v))
}

// MusicIDNEQ applies the NEQ predicate on the "music_id" field.
func MusicIDNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldMusicID, v))
}

// MusicIDIn applies the In predicate on the "music_id" field.
func MusicIDIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldMusicID, vs...))
}

// MusicIDNotIn applies the NotIn predicate on the "music_id" field.
func MusicIDNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldMusicID, vs...))
}

// MusicIDGT applies the GT predicate on the "music_id" field.
func MusicIDGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldMusicID, v))
}

// MusicIDGTE applies the GTE predicate on the "music_id" field.
func MusicIDGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldMusicID, v))
}

// MusicIDLT applies the LT predicate on the "music_id" field.
func MusicIDLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldMusicID, v))
}

// MusicIDLTE applies the LTE predicate on the "music_id" field.
func MusicIDLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldMusicID, v))
}

// MusicIDIsNil applies the IsNil predicate on the "music_id" field.
func MusicIDIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldMusicID))
}

// MusicIDNotNil applies the NotNil predicate on the "music_id" field.
func MusicIDNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldMusicID))
}

// MusicVocalTypeIsNil applies the IsNil predicate on the "music_vocal_type" field.
func MusicVocalTypeIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldMusicVocalType))
}

// MusicVocalTypeNotNil applies the NotNil predicate on the "music_vocal_type" field.
func MusicVocalTypeNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldMusicVocalType))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldSeq, v))
}

// SeqIsNil applies the IsNil predicate on the "seq" field.
func SeqIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldSeq))
}

// SeqNotNil applies the NotNil predicate on the "seq" field.
func SeqNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldSeq))
}

// ReleaseConditionIDEQ applies the EQ predicate on the "release_condition_id" field.
func ReleaseConditionIDEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldReleaseConditionID, v))
}

// ReleaseConditionIDNEQ applies the NEQ predicate on the "release_condition_id" field.
func ReleaseConditionIDNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldReleaseConditionID, v))
}

// ReleaseConditionIDIn applies the In predicate on the "release_condition_id" field.
func ReleaseConditionIDIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldReleaseConditionID, vs...))
}

// ReleaseConditionIDNotIn applies the NotIn predicate on the "release_condition_id" field.
func ReleaseConditionIDNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldReleaseConditionID, vs...))
}

// ReleaseConditionIDGT applies the GT predicate on the "release_condition_id" field.
func ReleaseConditionIDGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldReleaseConditionID, v))
}

// ReleaseConditionIDGTE applies the GTE predicate on the "release_condition_id" field.
func ReleaseConditionIDGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldReleaseConditionID, v))
}

// ReleaseConditionIDLT applies the LT predicate on the "release_condition_id" field.
func ReleaseConditionIDLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldReleaseConditionID, v))
}

// ReleaseConditionIDLTE applies the LTE predicate on the "release_condition_id" field.
func ReleaseConditionIDLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldReleaseConditionID, v))
}

// ReleaseConditionIDIsNil applies the IsNil predicate on the "release_condition_id" field.
func ReleaseConditionIDIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldReleaseConditionID))
}

// ReleaseConditionIDNotNil applies the NotNil predicate on the "release_condition_id" field.
func ReleaseConditionIDNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldReleaseConditionID))
}

// CaptionEQ applies the EQ predicate on the "caption" field.
func CaptionEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldCaption, v))
}

// CaptionNEQ applies the NEQ predicate on the "caption" field.
func CaptionNEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldCaption, v))
}

// CaptionIn applies the In predicate on the "caption" field.
func CaptionIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldCaption, vs...))
}

// CaptionNotIn applies the NotIn predicate on the "caption" field.
func CaptionNotIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldCaption, vs...))
}

// CaptionGT applies the GT predicate on the "caption" field.
func CaptionGT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldCaption, v))
}

// CaptionGTE applies the GTE predicate on the "caption" field.
func CaptionGTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldCaption, v))
}

// CaptionLT applies the LT predicate on the "caption" field.
func CaptionLT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldCaption, v))
}

// CaptionLTE applies the LTE predicate on the "caption" field.
func CaptionLTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldCaption, v))
}

// CaptionContains applies the Contains predicate on the "caption" field.
func CaptionContains(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContains(FieldCaption, v))
}

// CaptionHasPrefix applies the HasPrefix predicate on the "caption" field.
func CaptionHasPrefix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasPrefix(FieldCaption, v))
}

// CaptionHasSuffix applies the HasSuffix predicate on the "caption" field.
func CaptionHasSuffix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasSuffix(FieldCaption, v))
}

// CaptionIsNil applies the IsNil predicate on the "caption" field.
func CaptionIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldCaption))
}

// CaptionNotNil applies the NotNil predicate on the "caption" field.
func CaptionNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldCaption))
}

// CaptionEqualFold applies the EqualFold predicate on the "caption" field.
func CaptionEqualFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEqualFold(FieldCaption, v))
}

// CaptionContainsFold applies the ContainsFold predicate on the "caption" field.
func CaptionContainsFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContainsFold(FieldCaption, v))
}

// CharactersIsNil applies the IsNil predicate on the "characters" field.
func CharactersIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldCharacters))
}

// CharactersNotNil applies the NotNil predicate on the "characters" field.
func CharactersNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldCharacters))
}

// AssetbundleNameEQ applies the EQ predicate on the "assetbundle_name" field.
func AssetbundleNameEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldAssetbundleName, v))
}

// AssetbundleNameNEQ applies the NEQ predicate on the "assetbundle_name" field.
func AssetbundleNameNEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldAssetbundleName, v))
}

// AssetbundleNameIn applies the In predicate on the "assetbundle_name" field.
func AssetbundleNameIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldAssetbundleName, vs...))
}

// AssetbundleNameNotIn applies the NotIn predicate on the "assetbundle_name" field.
func AssetbundleNameNotIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldAssetbundleName, vs...))
}

// AssetbundleNameGT applies the GT predicate on the "assetbundle_name" field.
func AssetbundleNameGT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldAssetbundleName, v))
}

// AssetbundleNameGTE applies the GTE predicate on the "assetbundle_name" field.
func AssetbundleNameGTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldAssetbundleName, v))
}

// AssetbundleNameLT applies the LT predicate on the "assetbundle_name" field.
func AssetbundleNameLT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldAssetbundleName, v))
}

// AssetbundleNameLTE applies the LTE predicate on the "assetbundle_name" field.
func AssetbundleNameLTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldAssetbundleName, v))
}

// AssetbundleNameContains applies the Contains predicate on the "assetbundle_name" field.
func AssetbundleNameContains(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContains(FieldAssetbundleName, v))
}

// AssetbundleNameHasPrefix applies the HasPrefix predicate on the "assetbundle_name" field.
func AssetbundleNameHasPrefix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasPrefix(FieldAssetbundleName, v))
}

// AssetbundleNameHasSuffix applies the HasSuffix predicate on the "assetbundle_name" field.
func AssetbundleNameHasSuffix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasSuffix(FieldAssetbundleName, v))
}

// AssetbundleNameIsNil applies the IsNil predicate on the "assetbundle_name" field.
func AssetbundleNameIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldAssetbundleName))
}

// AssetbundleNameNotNil applies the NotNil predicate on the "assetbundle_name" field.
func AssetbundleNameNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldAssetbundleName))
}

// AssetbundleNameEqualFold applies the EqualFold predicate on the "assetbundle_name" field.
func AssetbundleNameEqualFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEqualFold(FieldAssetbundleName, v))
}

// AssetbundleNameContainsFold applies the ContainsFold predicate on the "assetbundle_name" field.
func AssetbundleNameContainsFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContainsFold(FieldAssetbundleName, v))
}

// ArchivePublishedAtEQ applies the EQ predicate on the "archive_published_at" field.
func ArchivePublishedAtEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtNEQ applies the NEQ predicate on the "archive_published_at" field.
func ArchivePublishedAtNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtIn applies the In predicate on the "archive_published_at" field.
func ArchivePublishedAtIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldArchivePublishedAt, vs...))
}

// ArchivePublishedAtNotIn applies the NotIn predicate on the "archive_published_at" field.
func ArchivePublishedAtNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldArchivePublishedAt, vs...))
}

// ArchivePublishedAtGT applies the GT predicate on the "archive_published_at" field.
func ArchivePublishedAtGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtGTE applies the GTE predicate on the "archive_published_at" field.
func ArchivePublishedAtGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtLT applies the LT predicate on the "archive_published_at" field.
func ArchivePublishedAtLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtLTE applies the LTE predicate on the "archive_published_at" field.
func ArchivePublishedAtLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldArchivePublishedAt, v))
}

// ArchivePublishedAtIsNil applies the IsNil predicate on the "archive_published_at" field.
func ArchivePublishedAtIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldArchivePublishedAt))
}

// ArchivePublishedAtNotNil applies the NotNil predicate on the "archive_published_at" field.
func ArchivePublishedAtNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldArchivePublishedAt))
}

// SpecialSeasonIDEQ applies the EQ predicate on the "special_season_id" field.
func SpecialSeasonIDEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDNEQ applies the NEQ predicate on the "special_season_id" field.
func SpecialSeasonIDNEQ(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDIn applies the In predicate on the "special_season_id" field.
func SpecialSeasonIDIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldSpecialSeasonID, vs...))
}

// SpecialSeasonIDNotIn applies the NotIn predicate on the "special_season_id" field.
func SpecialSeasonIDNotIn(vs ...int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldSpecialSeasonID, vs...))
}

// SpecialSeasonIDGT applies the GT predicate on the "special_season_id" field.
func SpecialSeasonIDGT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDGTE applies the GTE predicate on the "special_season_id" field.
func SpecialSeasonIDGTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDLT applies the LT predicate on the "special_season_id" field.
func SpecialSeasonIDLT(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDLTE applies the LTE predicate on the "special_season_id" field.
func SpecialSeasonIDLTE(v int) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldSpecialSeasonID, v))
}

// SpecialSeasonIDIsNil applies the IsNil predicate on the "special_season_id" field.
func SpecialSeasonIDIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldSpecialSeasonID))
}

// SpecialSeasonIDNotNil applies the NotNil predicate on the "special_season_id" field.
func SpecialSeasonIDNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldSpecialSeasonID))
}

// ArchiveDisplayTypeIsNil applies the IsNil predicate on the "archive_display_type" field.
func ArchiveDisplayTypeIsNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIsNull(FieldArchiveDisplayType))
}

// ArchiveDisplayTypeNotNil applies the NotNil predicate on the "archive_display_type" field.
func ArchiveDisplayTypeNotNil() predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotNull(FieldArchiveDisplayType))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Musicvocal {
	return predicate.Musicvocal(sql.FieldContainsFold(FieldServerRegion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Musicvocal) predicate.Musicvocal {
	return predicate.Musicvocal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Musicvocal) predicate.Musicvocal {
	return predicate.Musicvocal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Musicvocal) predicate.Musicvocal {
	return predicate.Musicvocal(sql.NotPredicates(p))
}
