// Code generated by ent, DO NOT EDIT.

package mysekaigatelevel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mysekaigatelevel type in the database.
	Label = "mysekaigatelevel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerRegion holds the string denoting the server_region field in the database.
	FieldServerRegion = "server_region"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldMysekaiGateID holds the string denoting the mysekai_gate_id field in the database.
	FieldMysekaiGateID = "mysekai_gate_id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldMysekaiGateMaterialGroupID holds the string denoting the mysekai_gate_material_group_id field in the database.
	FieldMysekaiGateMaterialGroupID = "mysekai_gate_material_group_id"
	// FieldMysekaiGateCharacterVisitCountRateID holds the string denoting the mysekai_gate_character_visit_count_rate_id field in the database.
	FieldMysekaiGateCharacterVisitCountRateID = "mysekai_gate_character_visit_count_rate_id"
	// FieldPowerBonusRate holds the string denoting the power_bonus_rate field in the database.
	FieldPowerBonusRate = "power_bonus_rate"
	// Table holds the table name of the mysekaigatelevel in the database.
	Table = "mysekaigatelevels"
)

// Columns holds all SQL columns for mysekaigatelevel fields.
var Columns = []string{
	FieldID,
	FieldServerRegion,
	FieldGameID,
	FieldMysekaiGateID,
	FieldLevel,
	FieldMysekaiGateMaterialGroupID,
	FieldMysekaiGateCharacterVisitCountRateID,
	FieldPowerBonusRate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Mysekaigatelevel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServerRegion orders the results by the server_region field.
func ByServerRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerRegion, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByMysekaiGateID orders the results by the mysekai_gate_id field.
func ByMysekaiGateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMysekaiGateID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByMysekaiGateMaterialGroupID orders the results by the mysekai_gate_material_group_id field.
func ByMysekaiGateMaterialGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMysekaiGateMaterialGroupID, opts...).ToFunc()
}

// ByMysekaiGateCharacterVisitCountRateID orders the results by the mysekai_gate_character_visit_count_rate_id field.
func ByMysekaiGateCharacterVisitCountRateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMysekaiGateCharacterVisitCountRateID, opts...).ToFunc()
}

// ByPowerBonusRate orders the results by the power_bonus_rate field.
func ByPowerBonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerBonusRate, opts...).ToFunc()
}
