// Code generated by ent, DO NOT EDIT.

package cardcostume3d

import (
	"haruki-cloud/database/sekai/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLTE(FieldID, id))
}

// CardID applies equality check predicate on the "card_id" field. It's identical to CardIDEQ.
func CardID(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldCardID, v))
}

// Costume3DID applies equality check predicate on the "costume3_d_id" field. It's identical to Costume3DIDEQ.
func Costume3DID(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldCostume3DID, v))
}

// IsInitialObtainHair applies equality check predicate on the "is_initial_obtain_hair" field. It's identical to IsInitialObtainHairEQ.
func IsInitialObtainHair(v bool) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldIsInitialObtainHair, v))
}

// ServerRegion applies equality check predicate on the "server_region" field. It's identical to ServerRegionEQ.
func ServerRegion(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldServerRegion, v))
}

// CardIDEQ applies the EQ predicate on the "card_id" field.
func CardIDEQ(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldCardID, v))
}

// CardIDNEQ applies the NEQ predicate on the "card_id" field.
func CardIDNEQ(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNEQ(FieldCardID, v))
}

// CardIDIn applies the In predicate on the "card_id" field.
func CardIDIn(vs ...int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIn(FieldCardID, vs...))
}

// CardIDNotIn applies the NotIn predicate on the "card_id" field.
func CardIDNotIn(vs ...int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotIn(FieldCardID, vs...))
}

// CardIDGT applies the GT predicate on the "card_id" field.
func CardIDGT(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGT(FieldCardID, v))
}

// CardIDGTE applies the GTE predicate on the "card_id" field.
func CardIDGTE(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGTE(FieldCardID, v))
}

// CardIDLT applies the LT predicate on the "card_id" field.
func CardIDLT(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLT(FieldCardID, v))
}

// CardIDLTE applies the LTE predicate on the "card_id" field.
func CardIDLTE(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLTE(FieldCardID, v))
}

// CardIDIsNil applies the IsNil predicate on the "card_id" field.
func CardIDIsNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIsNull(FieldCardID))
}

// CardIDNotNil applies the NotNil predicate on the "card_id" field.
func CardIDNotNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotNull(FieldCardID))
}

// Costume3DIDEQ applies the EQ predicate on the "costume3_d_id" field.
func Costume3DIDEQ(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldCostume3DID, v))
}

// Costume3DIDNEQ applies the NEQ predicate on the "costume3_d_id" field.
func Costume3DIDNEQ(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNEQ(FieldCostume3DID, v))
}

// Costume3DIDIn applies the In predicate on the "costume3_d_id" field.
func Costume3DIDIn(vs ...int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIn(FieldCostume3DID, vs...))
}

// Costume3DIDNotIn applies the NotIn predicate on the "costume3_d_id" field.
func Costume3DIDNotIn(vs ...int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotIn(FieldCostume3DID, vs...))
}

// Costume3DIDGT applies the GT predicate on the "costume3_d_id" field.
func Costume3DIDGT(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGT(FieldCostume3DID, v))
}

// Costume3DIDGTE applies the GTE predicate on the "costume3_d_id" field.
func Costume3DIDGTE(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGTE(FieldCostume3DID, v))
}

// Costume3DIDLT applies the LT predicate on the "costume3_d_id" field.
func Costume3DIDLT(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLT(FieldCostume3DID, v))
}

// Costume3DIDLTE applies the LTE predicate on the "costume3_d_id" field.
func Costume3DIDLTE(v int64) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLTE(FieldCostume3DID, v))
}

// Costume3DIDIsNil applies the IsNil predicate on the "costume3_d_id" field.
func Costume3DIDIsNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIsNull(FieldCostume3DID))
}

// Costume3DIDNotNil applies the NotNil predicate on the "costume3_d_id" field.
func Costume3DIDNotNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotNull(FieldCostume3DID))
}

// IsInitialObtainHairEQ applies the EQ predicate on the "is_initial_obtain_hair" field.
func IsInitialObtainHairEQ(v bool) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldIsInitialObtainHair, v))
}

// IsInitialObtainHairNEQ applies the NEQ predicate on the "is_initial_obtain_hair" field.
func IsInitialObtainHairNEQ(v bool) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNEQ(FieldIsInitialObtainHair, v))
}

// IsInitialObtainHairIsNil applies the IsNil predicate on the "is_initial_obtain_hair" field.
func IsInitialObtainHairIsNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIsNull(FieldIsInitialObtainHair))
}

// IsInitialObtainHairNotNil applies the NotNil predicate on the "is_initial_obtain_hair" field.
func IsInitialObtainHairNotNil() predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotNull(FieldIsInitialObtainHair))
}

// ServerRegionEQ applies the EQ predicate on the "server_region" field.
func ServerRegionEQ(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEQ(FieldServerRegion, v))
}

// ServerRegionNEQ applies the NEQ predicate on the "server_region" field.
func ServerRegionNEQ(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNEQ(FieldServerRegion, v))
}

// ServerRegionIn applies the In predicate on the "server_region" field.
func ServerRegionIn(vs ...string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldIn(FieldServerRegion, vs...))
}

// ServerRegionNotIn applies the NotIn predicate on the "server_region" field.
func ServerRegionNotIn(vs ...string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldNotIn(FieldServerRegion, vs...))
}

// ServerRegionGT applies the GT predicate on the "server_region" field.
func ServerRegionGT(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGT(FieldServerRegion, v))
}

// ServerRegionGTE applies the GTE predicate on the "server_region" field.
func ServerRegionGTE(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldGTE(FieldServerRegion, v))
}

// ServerRegionLT applies the LT predicate on the "server_region" field.
func ServerRegionLT(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLT(FieldServerRegion, v))
}

// ServerRegionLTE applies the LTE predicate on the "server_region" field.
func ServerRegionLTE(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldLTE(FieldServerRegion, v))
}

// ServerRegionContains applies the Contains predicate on the "server_region" field.
func ServerRegionContains(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldContains(FieldServerRegion, v))
}

// ServerRegionHasPrefix applies the HasPrefix predicate on the "server_region" field.
func ServerRegionHasPrefix(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldHasPrefix(FieldServerRegion, v))
}

// ServerRegionHasSuffix applies the HasSuffix predicate on the "server_region" field.
func ServerRegionHasSuffix(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldHasSuffix(FieldServerRegion, v))
}

// ServerRegionEqualFold applies the EqualFold predicate on the "server_region" field.
func ServerRegionEqualFold(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldEqualFold(FieldServerRegion, v))
}

// ServerRegionContainsFold applies the ContainsFold predicate on the "server_region" field.
func ServerRegionContainsFold(v string) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.FieldContainsFold(FieldServerRegion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cardcostume3D) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cardcostume3D) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cardcostume3D) predicate.Cardcostume3D {
	return predicate.Cardcostume3D(sql.NotPredicates(p))
}
