// Code generated by ent, DO NOT EDIT.

package areaitemlevel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the areaitemlevel type in the database.
	Label = "areaitemlevel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAreaItemID holds the string denoting the area_item_id field in the database.
	FieldAreaItemID = "area_item_id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldTargetUnit holds the string denoting the target_unit field in the database.
	FieldTargetUnit = "target_unit"
	// FieldTargetCardAttr holds the string denoting the target_card_attr field in the database.
	FieldTargetCardAttr = "target_card_attr"
	// FieldTargetGameCharacterID holds the string denoting the target_game_character_id field in the database.
	FieldTargetGameCharacterID = "target_game_character_id"
	// FieldPower1BonusRate holds the string denoting the power1_bonus_rate field in the database.
	FieldPower1BonusRate = "power1_bonus_rate"
	// FieldPower1AllMatchBonusRate holds the string denoting the power1_all_match_bonus_rate field in the database.
	FieldPower1AllMatchBonusRate = "power1_all_match_bonus_rate"
	// FieldPower2BonusRate holds the string denoting the power2_bonus_rate field in the database.
	FieldPower2BonusRate = "power2_bonus_rate"
	// FieldPower2AllMatchBonusRate holds the string denoting the power2_all_match_bonus_rate field in the database.
	FieldPower2AllMatchBonusRate = "power2_all_match_bonus_rate"
	// FieldPower3BonusRate holds the string denoting the power3_bonus_rate field in the database.
	FieldPower3BonusRate = "power3_bonus_rate"
	// FieldPower3AllMatchBonusRate holds the string denoting the power3_all_match_bonus_rate field in the database.
	FieldPower3AllMatchBonusRate = "power3_all_match_bonus_rate"
	// FieldSentence holds the string denoting the sentence field in the database.
	FieldSentence = "sentence"
	// FieldServerRegion holds the string denoting the server_region field in the database.
	FieldServerRegion = "server_region"
	// Table holds the table name of the areaitemlevel in the database.
	Table = "areaitemlevels"
)

// Columns holds all SQL columns for areaitemlevel fields.
var Columns = []string{
	FieldID,
	FieldAreaItemID,
	FieldLevel,
	FieldTargetUnit,
	FieldTargetCardAttr,
	FieldTargetGameCharacterID,
	FieldPower1BonusRate,
	FieldPower1AllMatchBonusRate,
	FieldPower2BonusRate,
	FieldPower2AllMatchBonusRate,
	FieldPower3BonusRate,
	FieldPower3AllMatchBonusRate,
	FieldSentence,
	FieldServerRegion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Areaitemlevel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAreaItemID orders the results by the area_item_id field.
func ByAreaItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAreaItemID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByTargetUnit orders the results by the target_unit field.
func ByTargetUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetUnit, opts...).ToFunc()
}

// ByTargetCardAttr orders the results by the target_card_attr field.
func ByTargetCardAttr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCardAttr, opts...).ToFunc()
}

// ByTargetGameCharacterID orders the results by the target_game_character_id field.
func ByTargetGameCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetGameCharacterID, opts...).ToFunc()
}

// ByPower1BonusRate orders the results by the power1_bonus_rate field.
func ByPower1BonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower1BonusRate, opts...).ToFunc()
}

// ByPower1AllMatchBonusRate orders the results by the power1_all_match_bonus_rate field.
func ByPower1AllMatchBonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower1AllMatchBonusRate, opts...).ToFunc()
}

// ByPower2BonusRate orders the results by the power2_bonus_rate field.
func ByPower2BonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower2BonusRate, opts...).ToFunc()
}

// ByPower2AllMatchBonusRate orders the results by the power2_all_match_bonus_rate field.
func ByPower2AllMatchBonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower2AllMatchBonusRate, opts...).ToFunc()
}

// ByPower3BonusRate orders the results by the power3_bonus_rate field.
func ByPower3BonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower3BonusRate, opts...).ToFunc()
}

// ByPower3AllMatchBonusRate orders the results by the power3_all_match_bonus_rate field.
func ByPower3AllMatchBonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPower3AllMatchBonusRate, opts...).ToFunc()
}

// BySentence orders the results by the sentence field.
func BySentence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentence, opts...).ToFunc()
}

// ByServerRegion orders the results by the server_region field.
func ByServerRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerRegion, opts...).ToFunc()
}
