// Code generated by ent, DO NOT EDIT.

package resourceboxdetail

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resourceboxdetail type in the database.
	Label = "resourceboxdetail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceBoxID holds the string denoting the resource_box_id field in the database.
	FieldResourceBoxID = "resource_box_id"
	// FieldResourceQuantity holds the string denoting the resource_quantity field in the database.
	FieldResourceQuantity = "resource_quantity"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldResourceBoxPurpose holds the string denoting the resource_box_purpose field in the database.
	FieldResourceBoxPurpose = "resource_box_purpose"
	// FieldResourceLevel holds the string denoting the resource_level field in the database.
	FieldResourceLevel = "resource_level"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldServerRegion holds the string denoting the server_region field in the database.
	FieldServerRegion = "server_region"
	// Table holds the table name of the resourceboxdetail in the database.
	Table = "resourceboxdetails"
)

// Columns holds all SQL columns for resourceboxdetail fields.
var Columns = []string{
	FieldID,
	FieldResourceBoxID,
	FieldResourceQuantity,
	FieldResourceID,
	FieldResourceBoxPurpose,
	FieldResourceLevel,
	FieldResourceType,
	FieldServerRegion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Resourceboxdetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceBoxID orders the results by the resource_box_id field.
func ByResourceBoxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceBoxID, opts...).ToFunc()
}

// ByResourceQuantity orders the results by the resource_quantity field.
func ByResourceQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceQuantity, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByResourceBoxPurpose orders the results by the resource_box_purpose field.
func ByResourceBoxPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceBoxPurpose, opts...).ToFunc()
}

// ByResourceLevel orders the results by the resource_level field.
func ByResourceLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceLevel, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByServerRegion orders the results by the server_region field.
func ByServerRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerRegion, opts...).ToFunc()
}
