// Code generated by ent, DO NOT EDIT.

package resourceboxe

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resourceboxe type in the database.
	Label = "resourceboxe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerRegion holds the string denoting the server_region field in the database.
	FieldServerRegion = "server_region"
	// FieldResourceBoxPurpose holds the string denoting the resource_box_purpose field in the database.
	FieldResourceBoxPurpose = "resource_box_purpose"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldResourceBoxType holds the string denoting the resource_box_type field in the database.
	FieldResourceBoxType = "resource_box_type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAssetbundleName holds the string denoting the assetbundle_name field in the database.
	FieldAssetbundleName = "assetbundle_name"
	// Table holds the table name of the resourceboxe in the database.
	Table = "resourceboxes"
)

// Columns holds all SQL columns for resourceboxe fields.
var Columns = []string{
	FieldID,
	FieldServerRegion,
	FieldResourceBoxPurpose,
	FieldGameID,
	FieldResourceBoxType,
	FieldDescription,
	FieldDetails,
	FieldName,
	FieldAssetbundleName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Resourceboxe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServerRegion orders the results by the server_region field.
func ByServerRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerRegion, opts...).ToFunc()
}

// ByResourceBoxPurpose orders the results by the resource_box_purpose field.
func ByResourceBoxPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceBoxPurpose, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByResourceBoxType orders the results by the resource_box_type field.
func ByResourceBoxType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceBoxType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAssetbundleName orders the results by the assetbundle_name field.
func ByAssetbundleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetbundleName, opts...).ToFunc()
}
