// Code generated by ent, DO NOT EDIT.

package gameaccount

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gameaccount type in the database.
	Label = "game_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldBg holds the string denoting the bg field in the database.
	FieldBg = "bg"
	// EdgeBindings holds the string denoting the bindings edge name in mutations.
	EdgeBindings = "bindings"
	// Table holds the table name of the gameaccount in the database.
	Table = "game_accounts"
	// BindingsTable is the table that holds the bindings relation/edge.
	BindingsTable = "user_bindings"
	// BindingsInverseTable is the table name for the UserBinding entity.
	// It exists in this package in order to avoid circular dependency with the "userbinding" package.
	BindingsInverseTable = "user_bindings"
	// BindingsColumn is the table column denoting the bindings relation/edge.
	BindingsColumn = "game_account_id"
)

// Columns holds all SQL columns for gameaccount fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldServer,
	FieldBg,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// ServerValidator is a validator for the "server" field. It is called by the builders before save.
	ServerValidator func(string) error
)

// OrderOption defines the ordering options for the GameAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByBindingsCount orders the results by bindings count.
func ByBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBindingsStep(), opts...)
	}
}

// ByBindings orders the results by bindings terms.
func ByBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
	)
}
